### ISSUE TITLE
Can't use extend with factory closures

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/container#102]
It would be awesome to be able to use withMethodCall with CallableDefinition or at least have a method that would accept any callable and put the container value as the first argument. I need to be able to extend definitions from one provider to another:

``` php
//First provider

public function register() 
{
    $this->getContainer()->add('SomeClass', function() {return new SomeClass;});
}

//Second provider

public function boot()
{
    $this->getContainer()->extend('SomeClass')->withCallback(function($classObj, $otherArg) {
        $classObj->add($otherArg);
        return $classObj;
    }, ['otherArgFromContainer]);
}

```

What are your thoughts on this? Could it be added fast as a non breakable new feature? I can do a pull request if you want.

**Comment by philipobenito** [comment]
If I understand what you're trying to do then `extend` should already be able to do this?

**Comment by nebulousGirl** [comment]
No, because in the case of a factory closure, ``extend`` returns a [`` CallableDefinition``](https://github.com/thephpleague/container/blob/master/src/Definition/CallableDefinition.php) and it does not have any method that allows me to add another closure to extend it like in [`` ClassDefinition``](https://github.com/thephpleague/container/blob/master/src/Definition/ClassDefinition.php) with ``withMethodCall``.

To resolve this problem, I can add a ``withCallback`` method to ``AbstractDefinition``, I just want your opinion before I start working on it.

**Comment by philipobenito** [comment]
@nebulousGirl ah, I see what you mean. You could do this, seems a little like a work around but I think safer overall than enabling `withMethodCall`.

```php
$container
    ->add('something', function ($methods = []) {
        $service = new Service;

        foreach ($methods as $method => $args) {
            call_user_func_array([$service, $method], $args);
            // you could even go a little further here and have the container resolve $args
        }

        return $service;
    })
;

$container->get('something'); // no methods invoked as none passed to the callable

$container
    ->extend('something')
    ->withArgument(new RawArgument([
        'methodName' => [/* args */],
        'anotherMethod' => [/* args /*]
    ])
;

$container->get('something'); // methodName and anotherMethod both invoked
```

**Comment by philipobenito** [comment]
@nebulousGirl the problem with adding a method to AbstractDefinition is that it's flirting with a BC break if we want to keep interfaces up to date.

**Comment by nebulousGirl** [comment]
Would you prefer that I create a trait that is used both by CallableDefinition and ClassDefinition?

**Comment by philipobenito** [comment]
Hmm, I dunno, let me think on it for a day or so (a little busy today), my initial thoughts are that it's not a major change over my example above. Having reminded myself of the codebase, it would be fine as an addition to `AbstractDefinition`, we'd just need to add it to the interface on the next major version bump. I'm just not 100% sure on the semantics yet.

**Comment by Anahkiasen** [comment]
Any news on this one? Trying to make a decorator to support [service-providers](https://github.com/container-interop/service-provider) but I'm being blocked by the same issue :/

**Comment by philipobenito** [comment]
This is handled by 421d774 for release in `3.0.0`.

You can now add method calls to any definition and it will attempt to invoke those methods if the end concrete is an object.
