### ISSUE TITLE
Returning false from a factory closure results in the service not being added to the container

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/container#103]
Is it the intended behavior? What do I do if I want to return false from the closure?

**Comment by philipobenito** [comment]
It is intended yes, I originally considered allowing falsies to be returned but it allows too much blurring of what the container should be used for.

**Comment by gezpage** [comment]
I have been attempting to dynamically load config items as services, so config parameters can be easily passed as constructor args (database credentials, enabling / disabling display errors etc.). However for booleans this doesn't work and leads to an exception if a false is passed.

Assuming this is not what you intend the container to be used for, can you recommend a way to handle configuration arguments in container services?

**Comment by philipobenito** [comment]
Configuration I would generally pass as an array.
