### ISSUE TITLE
Impossible to override shared service if already resolved

### ISSUE THREAD

**Issue by Anahkiasen** [thephpleague/container#111]
I'm not sure if this is a bug or intended behavior so bear with me. If I share a value in the container, I am properly able to overwrite it:

``` php
$container = new League\Container\Container();

$container->share('foo', 'bar');
dump($container->get('foo')); // bar

$container->share('foo', 'baz');
dump($container->get('foo')); // baz
```

If however I share a factory, I can't overwrite it:

``` php
$container = new League\Container\Container();

$container->share('foo', function() {
    return 'bar';
});
dump($container->get('foo'));// bar

$container->share('foo', function() {
    return 'baz';
});
dump($container->get('foo')); // bar
```

Reason seems to be the container looks in `$this->shared` the second time even though the definition has changed, and thus it returns the resolved value. Shouldn't the resolved value be cleared when the definition changes?

**Comment by hannesvdvreken** [comment]
Hmm, yeah. Good explanation 👍

It seems appropriate to remove the shared object when the shared method is called again with the same key and register the new callback to resolve it the next time.

**Comment by Anahkiasen** [comment]
To add a precision, the issue also appears if I do this:

```php
$container = new League\Container\Container();

$container->share('foo', function() {
    return 'bar';
});
dump($container->get('foo'));// bar

$container->add('foo', function() {
    return 'baz';
});
dump($container->get('foo')); // bar
```

**Comment by philipobenito** [comment]
You're right, this is something I didn't think of, if you register something with an alias that has already been resolved as shared then it should clear out that shared object.

@hannesvdvreken is this a BC break? That would determine what happens from this point.

**Comment by Anahkiasen** [comment]
I would personally consider this a BC break, some people might have been relying on that behavior in some ways, thinking it was intended.

**Comment by hannesvdvreken** [comment]
What does container-interop say about this? Is there a general set of integration tests that every implementation needs to comply with?

**Comment by fimbulvetr** [comment]
I'm evaluating the adoption of this project, and this would really like to see this feature or a reasonable alternative accepted.

**Comment by odan** [comment]
I am using the latest stable version (3.2.2), but this behavior seems to have changed. It is not possible to "overwrite" items. It doesn't matter in which combination I use the `add` or `share` method. The result is always the same ("bar").

Example:

```php
$container = new \League\Container\Container();

$container->share('foo', function() {
    return 'bar';
});
dump($container->get('foo')); // bar

$container->share('foo', function() {
    return 'baz';
});
var_dump($container->get('foo')); // bar
```

My questions are: 

* Is this "feature" still available? 
* If yes, how can I overwrite an container item? 
* Is this kind of usage "good practice" or "bad practice"?
