### ISSUE TITLE
Add ability to register a Service Provider

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#12]
Reference: orno/di#32

**Comment by sagikazarmark** [comment]
Thinking about contribution, but this is whole new feature.

**Comment by philipobenito** [comment]
This is planned for v1.3.0 :+1:

**Comment by sagikazarmark** [comment]
@philipobenito do you have a schedule for this?

Here is the thing: we (FuelPHP team) are thinking about to use this for dependency injection. But we need service providers which we can do three ways:

1. Do it in an extension
2. Wait for you doing it
3 Contribute it back

Since I don't know your plans, I can't choose way. Also, I am not that familiar with the package, so I would leave it to you. :smile:

**Comment by hannesvdvreken** [comment]
I've recently implemented something like this using the orno container.
Lemme write it down how it looks like so you can comment on it.

**Comment by sagikazarmark** [comment]
@hannesvdvreken looking forward to it ;)

**Comment by philipobenito** [comment]
@hannesvdvreken have you implemented anything yet? If not was going to take a look today

**Comment by hannesvdvreken** [comment]
Let me write it down in a couple of hours. Mitigating a storm of incoming notifications and context switches first.

**Comment by philipobenito** [comment]
:+1: cheers

**Comment by philipobenito** [comment]
Solved by active PR #18 to be merged for version 1.3.0
