### ISSUE TITLE
PSR-11 (ContainerInterface)

### ISSUE THREAD

**Issue by odan** [thephpleague/container#122]
Hi, the PSR-11 (ContainerInterface) has been accepted. bit.ly/2lGHGz8

Currently this package (thephpleague/container) provides the "container-interop/container-interop-implementation" v.1.1. So it should be "easy" to migrate to v.1.2 (PSR-11) right? 

> Starting Feb. 13th 2017, container-interop is officially deprecated in favor of PSR-11. Container-interop has been the test-bed of PSR-11. From v1.2, container-interop directly extends PSR-11 interfaces. Therefore, all containers implementing container-interop are now de-facto compatible with PSR-11.

When are you planing to "update" from "container-interop/container-interop" v.1.1 to v1.2 (PSR-11)?

**Comment by philipobenito** [comment]
This requires no action in regard to container interop as a composer update will bring in the change. However there will be a breaking change update to depend directly on PSR-11 some time in the near future.

**Comment by hannesvdvreken** [comment]
@philipobenito correct me if I'm wrong but... you can just add a implements PsrContainerInterface, no? It's just a new minor version. Look at this PR to Symfony to see what I mean:

https://github.com/symfony/symfony/pull/21265

Cheers

**Comment by philipobenito** [comment]
@hannesvdvreken Correct but I have some other BC changes planned so makes sense to all come together and remove the middleman dependency.

**Comment by hannesvdvreken** [comment]
Ah, I see. Didn't know stuff was about to change.

But are you open for small incremental steps to allow PSR-11 now? Instead of holding it off until rewrite is ready?

Seen #123? just asking.

**Comment by philipobenito** [comment]
Just Looking :-)

**Comment by philipobenito** [comment]
@XedinUnknown very good catch, and I'm not sure how this works either, it must fallback from the alias if there isn't a clash. Will test that out later to see if it's the case
