### ISSUE TITLE
Adding a static class and don't initialise on ->get()

### ISSUE THREAD

**Issue by CMCDragonkai** [thephpleague/container#124]
Is there a way to add a class that stays static, so when you `$container->get('Class')` it, it remains a static class so that you can perform `$class::method` instead of `$object->method()`?

**Comment by CMCDragonkai** [comment]
Isn't it possible to then pass subclasses in place of code that requires the parent class?

**Comment by hannesvdvreken** [comment]
I wouldn't recommend using static methods or classes. Use interfaces and different implementations instead. Look into SOLID principles.

Cheers

**Comment by philipobenito** [comment]
@CMCDragonkai Just to elaborate on what @hannesvdvreken said, you don't gain any benefit from having a container manage any classes that implement static methods. It's not a limitation of this library, it's just how static access works as you are not dealing with an object when invoking static methods.

**Comment by CMCDragonkai** [comment]
I'm working with the rmccue Requests library, and it's usage is through static methods. Is it not possible to pass subclasses just like passing subobjects?

**Comment by localheinz** [comment]
@CMCDragonkai 

If you can, try using a PSR-7 implementation!

For reference, see

* https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md
* https://github.com/php-fig/http-message
* https://github.com/zendframework/zend-diactoros
