### ISSUE TITLE
API methods missing in docs

### ISSUE THREAD

**Issue by piotr-cz** [thephpleague/container#128]
Please add documentation for following methods:

- `DefinitionInterface::withArguments`
- `ClassDefinitionInterface::withMethodCall`
- `ClassDefinitionInterface::withMethodCalls`

**Comment by philipobenito** [comment]
The singular `withMethodCall` is documented here: http://container.thephpleague.com/2.x/setter-injection/

The singular `withArgument` is documented here: http://container.thephpleague.com/2.x/constructor-injection/

The plural versions of these methods simply accept an array of each signature for the singular. I can will add a note of this once time permits. Feel free to send a PR in the meantime.

**Comment by piotr-cz** [comment]
That right, how could I miss these
