### ISSUE TITLE
Container::call() does not instantiate object

### ISSUE THREAD

**Issue by plashenkov** [thephpleague/container#130]
I'm trying to understand the logic of `Container::call()` method. I found nothing in the documentation about it, it is not used internally as well.

I hoped this method will allow me to call any method using autowiring. Something like this:

```php
class A
{

}

class B {
    public function someMethod(A $a)
    {
        var_dump($a);
    }
}

$container = new \League\Container\Container;
$container->delegate(new \League\Container\ReflectionContainer);

$container->call('B::someMethod');
```

But it does not work.
Here: https://github.com/thephpleague/container/blob/master/src/ReflectionContainer.php#L60
you explode string into two strings; later the first string (the class name) goes into `invokeArgs()` as a first parameter: https://github.com/thephpleague/container/blob/master/src/ReflectionContainer.php#L70
But this is a string, not an object.

It looks like this variant:
```php
$container->call([new B, 'someMethod']);
```
works, but I do not want to instantiate `B` manually. I would like the container to create it (it can be shared, its constructor can have other dependencies, etc.).

**Comment by ImEmil** [comment]
Hello, I've also encountered this issue before. I solved it by adding
```php
if (is_string($callable[0])) {
    $callable[0] = $this->getContainer()->get($callable[0]);
}
```
after [https://github.com/thephpleague/container/blob/master/src/ReflectionContainer.php#L64](url).

This is probably a bad way to solve but seems like the only way too.

**Comment by philipobenito** [comment]
Can confirm that this is a reproducible bug. @ImEmil has the correct solution at first glance, I just need to confirm that it bubbles out correctly.

**Comment by plashenkov** [comment]
Thank you! 🎉
