### ISSUE TITLE
Pass Container to a factory closure

### ISSUE THREAD

**Issue by plashenkov** [thephpleague/container#131]
Maybe it is a good idea to get Container instance as an argument in a factory closure, as it is done in Pimple:

```php
$container->share('service', function ($c) {
    return new \Some\Service(
        $c->get('another-service'),
        $c->get('yet-another-service')
    );
});
```

I know we can use `use ($container)`, but having container as an argument can be a little bit more convenient. Maybe there can be some scenarios (for example, when a closure is not a simple closure, but some other variant of callable) where this variant will be even more preferred.

**Comment by philipobenito** [comment]
This is something I was considering for `3.x` which is currently in a working PR #126, I'll add it as part of that.

**Comment by philipobenito** [comment]
@plashenkov there is a slight possible issue with this. You are already able to pass arguments to a closure to be resolved, meaning that it may be unclear what the signature of the callable should be.

So you might do this to get access to the container.

```
$container->share('service', function ($c) {
    return new \Some\Service(
        $c->get('another-service'),
        $c->get('yet-another-service')
    );
})
    ->withArgument($container)
;
```

I think this provides more control for the end user. It should just be documented in a better way.

**Comment by piotr-cz** [comment]
Would that work with Auto Wiring?
I mean wouldn't the container be passed to constructor during initialization when using

```php
$container->share(Service::class)l
```

**Comment by philipobenito** [comment]
Autowiring doesn't deal with closures.

If you used share, it would be passed to the callable the first time it was resolved, every subsequent retrieval of that service would return the already resolved result of your callable.
