### ISSUE TITLE
How to use ContainerAwareInterface

### ISSUE THREAD

**Issue by slier81** [thephpleague/container#132]
Hi there

Is there any tutorial on how to use `ContainerAwareInterface` ?

I try to pass the container object to my Controller class.

I cant find any tutorial on that..Please advice

Here what i tried:

Controller class:

```
<?php namespace App\Core;

use League\Container\ContainerAwareTrait;
use League\Container\ContainerAwareInterface;

class AppController implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    public function __get( $name ) {

        var_dump($this->container);
        exit;

        if ( $this->container->get( $name ) ) {
            return $this->container->get( $name );
        }
    }
}
```

Bootstrap script:
```

$container = new Container();

#Auto-wiring based on constructor typehints.
#http://container.thephpleague.com/auto-wiring
$container->delegate( new ReflectionContainer() );

$container->inflector( 'ContainerAwareInterface' )
    ->invokeMethod( 'setContainer', [ $container ] );
```

I got  the following when i try dump the container object

> /var/www/html/foo/src/App/Core/AppController.php:12:null

**Comment by hannesvdvreken** [comment]
I believe the mistake is in here:

```
$container->inflector('ContainerAwareInterface')
```

Try:

```
$container->inflector(\League\Container\ContainerAwareInterface::class)
```
or something equivalent.

**Comment by philipobenito** [comment]
@hannesvdvreken is correct, it has to be the fully qualified class name

**Comment by slier81** [comment]
i changed this line 

```
$container->inflector( 'ContainerAwareInterface' )
    ->invokeMethod( 'setContainer', [ $container ] );
```

to this

$container
    ->inflector(\League\Container\ContainerAwareInterface::class )
    ->invokeMethod( 'setContainer', [ $container ] );

yet i got error :

> Call to a member function has() on null

**Comment by alanondra** [comment]
Did this work for you, @slier81? Personally I'm still getting nulls where the container is requested in other objects' constructors.

```
PHP Catchable fatal error:  Argument 1 passed to App\Foo::__construct() must be an instance of App\Container, none given in /var/www/scripts/bridge-adapter/app/Foo.php on line 16
```

**Comment by slier81** [comment]
@alanondra yes it work, i need to fully qualify the container class as informed by @hannesvdvreken 

maybe you can show your code , so i can help you

**Comment by alanondra** [comment]
I didn't have the problem of not using the full class path. It's just not attempting to actually resolve the dependency on the Container instance, and I was wondering if this is actually the prescribed method of resolving it. I can use `withArgument` to force it to pass my container instance but that defeats the purpose of autowiring. Using `share` also does not expose the container instance. It just doesn't work.

```
use League\Container\ReflectionContainer;
use League\Container\ContainerAwareInterface;

// extends League\Container\Container
$container = new App\Container();

$container->delegate(new ReflectionContainer());

$container->inflector(ContainerAwareInterface::class)
	->invokeMethod('setContainer', [$app]);
```

**Comment by slier81** [comment]
```
$container->inflector(ContainerAwareInterface::class)
	->invokeMethod('setContainer', [$container]); // <--- pass the container
```

**Comment by alanondra** [comment]
Actually that's a typo from cleaning up the copy.

**Comment by slier81** [comment]
@alanondra 

int the class u expect to use the container u have to implement `ContainerAwareInterface`

Then use the `ContainerAwareTrait` to actually implement the `ContainerAwareInterface`

**Comment by alanondra** [comment]
I'm actually doing that, even though it defeats the purpose of autowiring. It still doesn't resolve the Container.

**Comment by philipobenito** [comment]
@alanondra 

Auto wiring only attempts to resolve constructor arguments. Inflectors are a completely separate feature. 

Firstly, I would not recommend injecting the container in to your classes unless they are a factory of some kind, that is service location and is considered an anti pattern and should be avoided when possible.

Secondly, I would always recommend being explicit with your definitions, auto wiring uses reflection which is slow, so I would only ever consider using it for prototyping before explicitly defining your classes with the container.

For your specific problem here, I see you are extending the container, without seeing what you're doing on top of this container I'm not aware of any side effects you might have introduced. Try accessing the container directly and see if that solves your problem, then you will know where the issue is.

**Comment by alanondra** [comment]
>Firstly, I would not recommend injecting the container in to your classes unless they are a factory of some kind, that is service location and is considered an anti pattern and should be avoided when possible.

Service location is something like using named database connections. There is only one instance of this expected to be used, so it's not service location.

>Secondly, I would always recommend being explicit with your definitions, auto wiring uses reflection which is slow, so I would only ever consider using it for prototyping before explicitly defining your classes with the container.

So there's really no point using this, then.

**Comment by philipobenito** [comment]
Hence...

> unless they are a factory of some kind

**Comment by alanondra** [comment]
So this would be considered an anti-pattern if, for instance, one wished to use it to share an instance of the PSR-7 ServerRequest, even though realistically this is probably the only request the application is actually handling?

**Comment by philipobenito** [comment]
No, but if you passed the container in to a controller or similar and pulled dependencies from the container, then it would be.

**Comment by alanondra** [comment]
So the purpose I suppose is that DI should never, ever be used outside of the container itself or providers hooked onto it.

**Comment by philipobenito** [comment]
No, the opposite, your classes should have no knowledge of the container, the container is just a tool that helps wire them together.
