### ISSUE TITLE
Using delegate ReflectionContainer not actually working

### ISSUE THREAD

**Issue by alanondra** [thephpleague/container#133]
I have it structured this way so that certain functionality is expected to happen within the application out-of-the-box, and using static accessors to relate to certain objects instead of allowing random string aliases means an IDE that uses PHPDocs can piece together what functionality exists and how to use it.

```
<?php

namespace App;

use League\Container\Container;
use League\Container\ReflectionContainer;

/**
 * @property-read \App\Arguments $arguments
 * @property-read \App\Router $router
 */
class Application extends Container
{
    protected static $accessors = [
        'arguments' => Arguments::class,
        'router' => Router::class,
    ];

    public function __construct(array $argv)
    {
        parent::__construct();

        $this->delegate(new ReflectionContainer());

        $this->share(static::class, $this);
        $this->share(static::$accessors['arguments'], Arguments::parse($argv));
        $this->share(static::$accessors['router']);
    }

    public function __get($property)
    {
        if (key_exists($property, static::$accessors)) {
            $accessor = static::$accessors[$property];
            return $this->get($accessor);
        }
        return null;
    }
}
```

Unfortunately it doesn't seem to want to resolve anything beyond the initial retrieval phase. It will attempt to get an instance of my `Router` class but it won't try to resolve any of its constructor dependencies, even if I merely use `stdClass` which has no expectations whatsoever. It just doesn't pass in anything.

**Comment by philipobenito** [comment]
I'll need more info than this, classes you're trying to resolve, their dependencies, whether they're defined with the main container (as the delegate will do nothing if they are). Is `key_exists` a custom function? What is happening there? Does the resolution work if you access the container directly?

I can see from the code above that the two elements of the `$accessors` array are being defined in the container, if you attempt to resolve those, `ReflectionContainer` will do nothing as an explicit definition will be found.

Based on that, it looks as though only those two properties can ever be accessed, there for will never be passed to the delegate.

**Comment by alanondra** [comment]
>Is `key_exists` a custom function?

`key_exists` is an [official alias of `array_key_exists`](http://php.net/manual/en/function.key-exists.php)

>I can see from the code above that the two elements of the $accessors array are being defined in the container, if you attempt to resolve those, ReflectionContainer will do nothing as an explicit definition will be found.

The documentation makes no mention of the fact that it will make no attempt whatsoever to try to resolve any dependencies of a sparsely-defined shared instance. If I were trying to pass in an actually defined instance in the second parameter, this would be understandable, but it seemed intuitive that it would try to resolve it if you didn't go through actually creating an instance, then add it to the list of shared entities vs. models that must have new instances created each time `get` is run.

I was hoping that doing so would merely say "don't create a new one whenever this is requested, just get it once, but still use DI to resolve it."

**Comment by philipobenito** [comment]
> Delegates are a way to allow you to register one or multiple backup containers that will be used to attempt the resolution of services when they cannot be resolved via this container.

I'll make this a little more explicit when I get chance. 

By attempting to mix resolutions, I am making an assumption about what the user wants to do, I have also seen this cause a lack of understanding in what is actually happening during the resolution process so the decision was made to make this explicit, if not found, fallback to the delegates, but only if it's not found.

**Comment by alanondra** [comment]
You've said a lot that I'm sure makes sense for the particular use cases you have defined, but I am no closer to a resolution.

**Comment by philipobenito** [comment]
Feel free to email me for what you're trying to achieve and I can attempt to help.
