### ISSUE TITLE
3.x docs on "Factories" gives 404 error

### ISSUE THREAD

**Issue by ncraike** [thephpleague/container#136]
[This page](http://container.thephpleague.com/3.x/factories/) referenced in the [3.x documentation's](http://container.thephpleague.com/3.x/) navigation gives an HTTP 404 error page on access.

**Comment by itsjavi** [comment]
What's the status of this project, isn't it maintained anymore?

**Comment by philipobenito** [comment]
Yes it is still maintained, a new major release is due, it's been waiting
for adoption of PHP 7+ to rise as well as a time to coincide with
league/route.

404 on upcoming release docs can be expected as they are still in
development.

**Comment by itsjavi** [comment]
Ok, it's good to know, thank you for the quick answer @philipobenito 
I am using it in my company and since we are migrating from PHP 7.0 to 7.2 I was a bit concerned.
