### ISSUE TITLE
Support factory closures defined from other services

### ISSUE THREAD

**Issue by ncraike** [thephpleague/container#137]
I'm not sure if this is truly a feature request, as it looks like some code has already been added to support this.

Some other DI systems allow defining factory services from methods of other services, using the DI alias for the other service. For example, a common pattern in Symfony config (using YAML syntax) is to define a repository factory like this:

```yaml
services:
    my_project.repository.my_entity:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - MyProjectBundle\Entity\MyEntity
```

This is equivalent to defining a factory closure which accepts the `doctrine.orm.entity_manager` service, and then returns `$entityManager->getRepository(MyEntity::class)`. This might be written in League with something like:

```php
$container
    ->add('my_project.repository.my_entity', function($entityManager) {
        return $entityManager->getRepository(MyEntity::class);
    })
    ->withArgument('doctrine.orm.entity_manager');
```

It looks like [part of `CallableDefinition`](https://github.com/thephpleague/container/blob/master/src/Definition/CallableDefinition.php#L15) may already support this with a syntax like:

```php
$container
    ->add(
        'my_project.repository.my_entity',
        ['doctrine.orm.entity_manager', 'getRepository`]
    )
    ->withArgument(MyEntity::class);
```

Particularly, the `if (is_array($this->concrete) && is_string($this->concrete[0])) {` condition appears to be checking for exactly this case: if the "callable" is an array, and the first element is a service alias to be resolved.

However, this code is never activated because of the `is_callable($concrete)` check [in `DefinitionFactory`](https://github.com/thephpleague/container/blob/master/src/Definition/DefinitionFactory.php#L16). `is_callable()` won't return true for an array like `['doctrine.orm.entity_manager', 'getRepository']`. I believe this is because "doctrine.orm.entity_manager" is not a valid class name. I haven't tested yet if everything just works if `$concrete[0]` is both a valid PHP class name and a defined service alias.

Are factory closures intended to be definable this way? Is `['service_alias', 'method_name']` the supported syntax?

If not, what are the checks [in `DefinitionFactory`](https://github.com/thephpleague/container/blob/master/src/Definition/DefinitionFactory.php#L16) use for?

**Comment by philipobenito** [comment]
It is intended to work that way but was only intended to work with array callables where the first element is a valid classname, this does work as intended currently.

I think however that I could switch things around to attempt to resolve the first element before an `is_callable` check, I don't think the performance hit would be too bad for that but I'd need to double check when I have a little more time. Probably be able to have a look in the next few days.

(Apologies for the late reply, this issue seemed to pass me by and I've only just seen it).

**Comment by ncraike** [comment]
Thank you for the response.
