### ISSUE TITLE
Fatal error: Interface 'League\Container\ContainerInterface' not found

### ISSUE THREAD

**Issue by mfprimo** [thephpleague/container#144]
With the current master branch, the basic code

```
require_once 'vendor/autoload.php';
$container = new League\Container\Container();
```
generates an error:
```
Fatal error: Interface 'League\Container\ContainerInterface' not found
```
since the source of Container is

```
namespace League\Container;

use Interop\Container\ContainerInterface as InteropContainerInterface;
...
class Container implements ContainerInterface
{
```

but `League\Container\ContainerInterface` has been disappeared somewhere between branches 2.x and master.
I think the correct declaration must omit the alias ` as InteropContainerInterface` in the use clause
or specify `implements InteropContainerInterface` in the class declaration.

**Comment by alphaliaud** [comment]
Hi,

I have the same problem.. Have you already resolved?

**Comment by mfprimo** [comment]
No,
  I used the old version, with:

        "league/container": "2.x",

in composer.json

**Comment by philipobenito** [comment]
Hi, when you were reporting this, 2.x was not the *older version*, it was current, anything newer was in active development as was stated on the README. I can't see that this is an issue in the 2.x branch so can only assume you must have been using the development branch so will close this for now, if it continues to be a problem, feel free to open again.
