### ISSUE TITLE
Default behavior for sharing doesn't adhere to PSR-11 recommendations

### ISSUE THREAD

**Issue by stivni** [thephpleague/container#148]
In PSR-11 I read this:

> Two successive calls to `get` with the same _identifier_ SHOULD return the same _value_. However, depending on the _implementor_ design and/or _user_ configuration, different values might be returned.

So while it gives the room to implementors to do things differently, it still recommends that two consecutive `get` calls to a container, _should_ return the same _value_. (And in my interpretation, the same _value_, also means the same _instance_ when it concerns service objects).

Too bad this library doesn't adhere to this behavior in its defaults, because as far as I know, containers are there mostly to _share_ services, which you normally only need to instantiate once.

Some places at which I think defaults should better be differently:

- the `add` method should be better of being shared by default.
- the ReflectionContainer should return the same instance every time something is called.
- (maybe there are more that it didn't discover yet?)

This is of course breaking compatibility, so just missed the boat for 3.0. Although I do think that making or providing a `SharingReflectionContainer` and/or being able to configure your container to _share everything_ by default, should be possible with this library and maybe even recommended in the docs.

I'd like to know what you think of this, because being able to configure `container` in such a way that it shared everything by default, might already have save our team some nasty bugs...

**Comment by hannesvdvreken** [comment]
Quick reply on the SharinReflectionContainer: A sharingreflectioncontainer
could be built very easily by wrapping a reflection container and caching
results returned by the reflection container. If you make it implement the
right interfaces you can pass it on to the main container using
$container->delegete($sharingReflectionContainer);.

**Comment by philipobenito** [comment]
Just to save any unnecessary work, sharing won’t ever be default behaviour for add, however, it was brought to my attention yesterday that I mistakenly removed the share method (basically a proxy to add that always marks the definition as shared) in 3.0.0 so that’ll will be reintroduced in the next couple of days.

I would be open to an extension of the reflection container or an option on it to cache results. Feel free to create a PR. If not then I’ll look at it when I get chance.

**Comment by philipobenito** [comment]
@stivni https://github.com/thephpleague/container/releases/tag/3.1.0 this should cover what you want, it's not by default though

**Comment by jenssegers** [comment]
I do agree with @stivni that when I read:

> Two successive calls to get with the same identifier SHOULD return the same value. However, depending on the implementor design and/or user configuration, different values might be returned.

I would expect `share` to be the default behaviour unless you specify otherwise. Isn't PHP-DI also shared by default?

**Comment by philipobenito** [comment]
I don’t disagree with the interpretation, but SHOULD is not MUST and for my purposes I’ve always preferred not shared by default, I think the recent release and your PR is a good enough compromise.
