### ISSUE TITLE
defaultToShared option now blocks non-shared definitions

### ISSUE THREAD

**Issue by jenssegers** [thephpleague/container#149]
Hey @philipobenito,

Thanks for adding back the `share` method and a `defaultToShared` option!

But when looking at the code now, it is now impossible to add a non-shared definition to the container when the `defaultToShared` option is set to `true`.

Would be handy to have `defaultToShared` set to `true`, and still be able to do this:

```
$container->add(Foo::class, ..., false);
```

**Comment by philipobenito** [comment]
That’s a fair point, will have a look later

**Comment by jenssegers** [comment]
@philipobenito Made a PR with a possible fix https://github.com/thephpleague/container/pull/150
