### ISSUE TITLE
Alert developer to circular dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#15]
Do this package allow recursive dependencies?

``` php
class Recursive 
{
    public function __construct(Recursive $recursive) { }
}
```

**Comment by hannesvdvreken** [comment]
No. How would a container be able to detect this?

**Comment by sagikazarmark** [comment]
``` php
protected $buildStack = [];

public function get($alias, array $args = [])
{
    if (in_array($alias, $this->buildStack)) {
        throw new Exception('Recursive dependency');
    }

    $this->buildStack[] = $alias;

    // some code

    array_pop($this->buildStack);

    // return
}
```

**Comment by hannesvdvreken** [comment]
That is clear, yes, thanks. And how would it be able to "allow" recursive
dependencies?

**Comment by philipobenito** [comment]
This isn't something that's planned, mainly because I don't want to
advocate doing that, I personally see it as a code smell.

I'll be taking a look at all PRs and issues this week as I've been away
this last week. At that point I'll be asking for input on the roadmap I've
been building.

**Comment by sagikazarmark** [comment]
No, this check could help avoiding recursive dependencies. You might
accidentally create a recursive dependency when building a big dependency
tree.

**Comment by philipobenito** [comment]
I may be open to a check, as I say I'll look this week :-)

**Comment by philipobenito** [comment]
Thoughts on when to detect dependency loops? On register or on attempt to resolve?

**Comment by sagikazarmark** [comment]
On attempt to resolve of course. Unresolved dependencies does not worth to check.

**Comment by philipobenito** [comment]
@sagikazarmark :+1:

**Comment by philipobenito** [comment]
@sagikazarmark Going to save this for the next patch as there are a few considerations to make about the different methods of resolving.

**Comment by sagikazarmark** [comment]
@philipobenito ok, but I think this is completely independent of the resolving logic itself. It is basically a check if the same alias is already being resolved. If yes, an exception is thrown.

**Comment by philipobenito** [comment]
The circular reference might be much deeper than that though, just want to write some test cases before I implement.

**Comment by sagikazarmark** [comment]
Much deeper? Why is that a problem? Every alias is resolved the same way (via the `get` method). If you build a list of aliases being resolved, you can catch it.

We want to break the chain at the very first occurence of recursive dependency.

But I leave it to you.

**Comment by philipobenito** [comment]
They are yes, however, there are multiple places where we invoke `get` so I just want to ensure we catch them all. Only suggesting a couple of days delay.

**Comment by sagikazarmark** [comment]
No problem :+1:

**Comment by philipobenito** [comment]
An exception is to be thrown when a circular reference is detected as the current error is unhelpful.
