### ISSUE TITLE
Unable to overwrite previous definitions

### ISSUE THREAD

**Issue by jenssegers** [thephpleague/container#151]
In version 2.x it was possible to overwrite previously added services on the container. Since 3.x appends definitions to the internal definitions array, the first definition added will always be returned.

Are there plans to bring this back to 3.x so that this is possible?

```
$container->add(Foo::class, $foo);
$container->add(Foo::class, $bar);

$bar === $container->get(Foo::class);
```

This is useful when doing functional tests when you boot your application+container and overwrite certain container definitions with mocks.

**Comment by jenssegers** [comment]
But how can you modify the definitions if they are already added to the container? You can't really access the internal definitions from outside the container.

**Comment by philipobenito** [comment]
The extend method gives you the definition object, you can edit that

**Comment by jenssegers** [comment]
Ok, so if there would be a `setConcrete` method, that would become:

```
$app->getContainer()->extend(Foo::class)->setConcrete($mock);
```

**Comment by philipobenito** [comment]
Correct
