### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted 

### ISSUE THREAD

**Issue by memran** [thephpleague/container#153]
I am using container version 3. I am trying to addServiceProvider from array through foreach loop. But it gives me error like this.

here is my function 

` public function registerAllServiceProviders()
      {
            $providers=$this->configArray['providers'];
            if(!is_array($providers)) {
                  throw new ArrayNotFoundException('Providers is not array');
              }
            // loop through service providers list
             foreach ($providers as $v) {
                   $this->addServiceProvider($v);
             }

      }
`

From above code i m getting the following error: 

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in vendor\league\container\src\ServiceProvider\ServiceProviderAggregate.php on line 59
`

but it works when i add service provider without loop like this .

`
$this->addServiceProvider("Application\ServiceProvider\ConfigServiceProvider");
$this->addServiceProvider("Application\ServiceProvider\RequestServiceProvider");
`

**Comment by philipobenito** [comment]
This doesn’t look to be an issue with container.

Your PHP install is running out of memory. Without knowing the structure/contents of your array or what else is happening in your application I couldn’t help you debug this.
