### ISSUE TITLE
register function being invoked on all service providers

### ISSUE THREAD

**Issue by warrenspence** [thephpleague/container#154]
I have created a small script to illustrate this issue:
https://gist.github.com/warrenspence/2f1875f510d82b75d8e870c857612470

The script contains 2 service providers, one always returns true for the `provides` function and the other always returns false.

Both service providers have their `register` function invoked as part of the `container/src/ServiceProvider/ServiceProviderAggregate.php` register function.

I would have expected that the register function of the second service provider would not be invoked.

**Comment by philipobenito** [comment]
Is the script you’ve provided the actual one you’ve used to test? There’s a bigger problem if so as that code should throw an exception as you haven’t added any definitions to the container before invoking get.

Would you be able to provide a PR with a failing test? If not, and the gist isn’t complete, could you please update it?

**Comment by warrenspence** [comment]
@philipobenito yes, the script in the gist runs successfully and produces the following output.
```
begin
service provider a: register
service provider b: register
end
```

The definition for 'hello' is added as part of the `register` function of ServiceProviderA
```
$this->getContainer()->add('hello', 'world');
```

**Comment by warrenspence** [comment]
Thanks.
