### ISSUE TITLE
How does phpstorm know what happens after $container->get?

### ISSUE THREAD

**Issue by hanwenbo** [thephpleague/container#155]
I want to make the development tips more friendly

**Comment by philipobenito** [comment]
I don’t use phpstorm so I’m not certain but it can’t know what happens after unless it’s doing some quite deep inspection

**Comment by hanwenbo** [comment]
@warrenspence Thank you very much. It will solve my problem

**Comment by maximegosselin** [comment]
You can typehint with a docblock just before the call to "container->get" so that the IDE knows which type of variable will be returned:

```php
/** @var MyServiceInterface $service */
$service = $container->get(MyServiceInterface::class);
```

I think this method is more portable because it doesn't only apply to PHPStorm...
