### ISSUE TITLE
Issue with registering several service providers.

### ISSUE THREAD

**Issue by mitrik** [thephpleague/container#156]
Hello,

I have an issue with registering several service providers.
Lets asume I have two service providers - **ServiceProvider1** provides **Service1** and **ServiceProvider2** provides **Service2**. 

I've add those two provides to container:

```php
$container->addServiceProvider(ServiceProvider1::class);
$container->addServiceProvider(ServiceProvider2::class);
```

Next, when I try to access **Service1** by getting it from container `$container->get(Service1::class)` then **ServiceProvider1** becomes registered in container (thanks to lazy loading approach). It happens in league/container/src/ServiceProvider/ServiceProviderAggregate.php in method "register".

When I try to access service **Service2** by getting it from container `$container->get(Service2::class)` then I get a fatal error with message:

> Uncaught Error: Maximum function nesting level of '256' reached, aborting! in league/container/src/ServiceProvider/ServiceProviderAggregate.php on line 73

It happens because of next piece of code:
```php
foreach ($this->getIterator() as $provider) {
    if (in_array($provider->getIdentifier(), $this->registered)) {
        return;
    } 

    if ($provider->provides($service)) {
        $provider->register();
        $this->registered[] = $provider->getIdentifier();
    }
}
```

**ServiceProvider1** added first to container and that provider is already registered at the moment when I try to access **Service2** from **ServiceProvider2**. So, method "register" from "ServiceProviderAggregate" class will always return when it found already registered provider.

I suppose that:
```php
if (in_array($provider->getIdentifier(), $this->registered)) {
    return;
} 
```
should be changed to:
```php
if (in_array($provider->getIdentifier(), $this->registered)) {
    continue;
} 
```

Best regards,
Dmytro Dmytrashchuk.

**Comment by philipobenito** [comment]
You’re correct, I will sort a big fix very this afternoon

**Comment by philipobenito** [comment]
Fixed with this release https://github.com/thephpleague/container/releases/tag/3.2.2
