### ISSUE TITLE
ServiceProviders may be aggregated multiple times

### ISSUE THREAD

**Issue by bwg** [thephpleague/container#157]
When adding the same service provider to a container, the service provider is added to the aggregate `providers` array regardless of whether it has already been added.

A use case would be 2 bootable service providers that have an internal dependency (add) a common service provider.

`Provider1->boot()` adds `Provider0`
`Provider2->boot()` adds `Provider0`

After `Provider1` and `Provider2` are added to the aggregate, `Provider0` exists in `providers` twice.

`Provider0` will only ever be registered once, but any `boot` method will be called each time it is added.

Additionally when resolving a dependency _not_ provided by `Provider0`, the redundant `Provider0` aggregates may be iterated.

The simplest fix would be to check the existence of the provider when adding
```php
    public function add($provider) : ServiceProviderAggregateInterface
    {
        if (is_string($provider) && $this->getContainer()->has($provider)) {
            $provider = $this->getContainer()->get($provider);
        } elseif (is_string($provider) && class_exists($provider)) {
            $provider = new $provider;
        }

        // return if provider has already been aggregated
        if (in_array($provider->getIdentifier(), $this->providers)) {
            return $this;
        }
```

However I wanted to understand if this behavior was intentional before submitting a PR.

Cheers,
Lee

**Comment by philipobenito** [comment]
Sorry for the late reply, I will have a look at this some time in the next week to determine the details and any change consequences

**Comment by bwg** [comment]
I'll just go ahead and submit a PR after the holidays.
