### ISSUE TITLE
Not work default value arguments with ioncube

### ISSUE THREAD

**Issue by dimaxz** [thephpleague/container#167]
https://github.com/thephpleague/container/blob/master/src/Argument/ArgumentResolverTrait.php#L74

with ioncube
Fatal error: Uncaught exception 
'League\Container\Exception\NotFoundException' with message 'Unable to 
resolve a value for parameter (tableName) in the function/method 
(__construct)' in 

example __construct($tableName = false){

**Comment by philipobenito** [comment]
By default, a container definition expects all arguments to be defined, this is intended.

**Comment by razonyang** [comment]
Maybe it is because of ioncube, any files contains reflection MUST be encoded with argument `--allow-reflection-all` or `--allow-reflection <pattern>`.
