### ISSUE TITLE
[rfc] Feature to automatically inject dependency when interface is implemented

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/container#17]
For example, when an object implements `ContainerAwareInterface` the container could be aware that when this is resolved, it should call a defined setter (`setContainer`) to inject something.

```php
$container = new League\Container\Container();

$container->context(League\Container\ContainerAwareInterface::class)
    ->withMethodCall('setContainer', [$container]);
```

Or something. The `context` method is just a temporary name. There must be a better suited name.

When an object which has this interface implemented, the `setContainer` method will be called automatically on the resolved object, right before the end of `$container->get(Vendor\MyClass::class)`.

**Comment by philipobenito** [comment]
:+1: sound good to me, will take a look when I get spare time

**Comment by philipobenito** [comment]
So thinking there doesn't need to be an extra method, as the last action within the `get` method could check if the result is an instance of `ContainerAwareInterface` and invoke `setContainer`.

**Comment by hannesvdvreken** [comment]
I would allow users to define the behaviour themselves. Not only for the `ContainerAwareInterface`, that's just an example.

**Comment by philipobenito** [comment]
So you're saying define a default behaviour for abstracts/interfaces? Then on resolution of the object, check our contexts and apply that behaviour if the result is an instance of a context?

**Comment by hannesvdvreken** [comment]
Yes exactly.

**Comment by philipobenito** [comment]
@alexbilbie suggested `inflector` as the method name, makes sense to me, you @hannesvdvreken ?

**Comment by hannesvdvreken** [comment]
👍

**Comment by philipobenito** [comment]
Usage as follows, will release when I've updated documentation.

```php
$container->inflector('Acme\SomeType')
          ->setProperty('property', 'value')
          ->setProperties([
              'property1' => 'value1',
              'property2' => 'value2'
          ]);

$container->inflector('Acme\SomeType')
          ->invokeMethod('someMethod', ['arg1', 'arg2'])
          ->invokeMethods([
              'method1' => ['arg1', 'arg2'],
              'method2' => ['arg1', 'arg2']
          ]);

$container->inflector('Acme\SomeType', function ($resolvedObject) {
    // do something with $resolvedObject 
});
```

Inflectors are the last thing to run on an object before it is returned to you via `get`. All property values and method arguments are run through the container to resolve an alias if a string points to one.
