### ISSUE TITLE
Give an IDE some love is possible.

### ISSUE THREAD

**Issue by kaxias** [thephpleague/container#180]
[https://github.com/thephpleague/container/blob/91a751faabb5e3f5e307d571e23d8aacc4acde88/src/ContainerAwareTrait.php#L37](https://github.com/thephpleague/container/blob/91a751faabb5e3f5e307d571e23d8aacc4acde88/src/ContainerAwareTrait.php#L37)

replace too
```
   /**
     * Get the container.
     *
     * @return \league\Container\Container|ContainerInterface
     */
```

**Comment by c00lmk** [comment]
The problem was not fixed, so why was this issue closed?
