### ISSUE TITLE
Code example image in the docs shows an example for version 2

### ISSUE THREAD

**Issue by timoschinkel** [thephpleague/container#185]
When navigating to the documentation of the package - https://container.thephpleague.com/ - an image with a code example is shown. But this code example uses the method `withArgument()`. This method seems to be replaced with `addArgument()` in the most recent version of the package.

I'm not sure what requirements you want to have on the image, which is why I did not create a PR to fix it.

**Comment by philipobenito** [comment]
will update it when I get a moment

**Comment by philipobenito** [comment]
Updated, sorry for the delay
