### ISSUE TITLE
Parameter missing and a suggestion

### ISSUE THREAD

**Issue by woxiangfy** [thephpleague/container#187]
Container.php file get method

line 162 change to

```
        $arrayOf = $this->definitions->resolveTagged($id,$new);
```

a suggestion:

add function

> hasTag
> getTag

**getTag**(Array returned )different from **get**。

**Comment by szepeviktor** [comment]
@philipobenito Should this be fixed?

May I send a PR?

**Comment by philipobenito** [comment]
Fixed in 3.3.1

**Comment by szepeviktor** [comment]
@philipobenito Could you elaborate in which commit?

**Comment by philipobenito** [comment]
There is only one commit in the release 93238f74ff5964aee27a78508cdfbdba1cd338f6

**Comment by szepeviktor** [comment]
Thank you.

It is missing from master :(

**Comment by philipobenito** [comment]
Yeah there's a mismatch on master currently, 3.x pointer is on 3.x branch now ready for 4.x release
