### ISSUE TITLE
Remove abandoned dependency

### ISSUE THREAD

**Issue by uberhacker** [thephpleague/container#190]
What is the best way to remove this warning?
```
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
```

**Comment by fridde** [comment]
I just had encountered the same issue.
But the simple solution is: 

Update *league/container* to anything above 3.0.

**Comment by philipobenito** [comment]
@uberhacker as @fridde says, that package has been removed from v3+
