### ISSUE TITLE
Cannot use an abstract definition defined in `register`, in `boot` method of a provider

### ISSUE THREAD

**Issue by Arcesilas** [thephpleague/container#192]
I've got this:

```php
    public function register()
    {
        $this->getContainer()->share(Environment::class, function () {
            $loader = new FilesystemLoader($this->geContainer()->get('path.views'));
            return new Environment($loader, [
                'cache' => $this->getContainer()->get('path.cache'),
            ]);
        });
    }

    public function boot()
    {
        $factory = $this->getContainer()->get(SmartControllerFactory::class);
        $factory->inflector(TwigAwareInterface::class)
            ->invokeMethod('setTwig', Environment::class);
    }
```

The `boot` method thorws an exception, because `Environment::class` is not defined. This means that the when `boot` method is executed, the container has not registered the service provider yet.
Is that by design?

I think the issue is in `ServieProviderAggregate`:

```php
        if ($provider instanceof BootableServiceProviderInterface) {
            $provider->boot();
        }

        if ($provider instanceof ServiceProviderInterface) {
            $this->providers[] = $provider;

            return $this;
        }
```

The latter `if` statement should be executed first, making the definitions it registers available in the `boot` method. Problem: this may introduce a BC break... I guess I should use my own `ServiceProviderAggregate` instance, right?

**Comment by philipobenito** [comment]
This is by design, the boot method runs before the register method to ensure everything in `register` is lazily loaded. If you need definitions available in the boot method, they need to be added to the container in that method.

**Comment by philipobenito** [comment]
From your example, the logic in your `boot` method can be moved to the `register` method. `boot` is designed for things like including required files etc

**Comment by Arcesilas** [comment]
> If you need definitions available in the boot method, they need to be added to the container in that method.

If I define the inflector in the `register` method, then it will never be applyed until the Twig `Environment` class is registered, which may be too late, right?

> From your example, the logic in your boot method can be moved to the register method.

I'm confused... SHould I move both to `register` or `boot`? I think I should put all in the `boot` method: I need the inflector at any time, then I should always register the Twig `Environment`.
Am I ok?

**Comment by philipobenito** [comment]
The `register` method is basically "on demand", the only time you would need Twig to be defined in `boot` is if, for example, you have an error handler that uses Twig templates, then it would be available to errors in bootstrapping the container (after the service provider for it is added). Other than that everything can be in `register`

**Comment by Arcesilas** [comment]
I've tried to put both in the `register` method, but then, Twig Environment is not injected in my Controller, while when setting the inflector in the `boot` method, it is...
Is I understand well, when setting the inflector, in `register`, it will be called when Twig `Environment` is required. First time the container meets a `TwigAwareInterface` instance, it does not know about the inflector and the instance does not require Twig. When, in the controller, I'll need Twig to create the view, then it won't be injected, because the inflector won't have been set. If an object need Twig at some point, then it would set the inflector and only then `TwigAwareInterface`s would have Twig injected.

So for now, I use a custom `ServiceProviderAggregate`. Since it's by design, I need another design. I could have used another service provider, or I guess I could have set the inflector somewhere else (when initializing my application, for example, after registering service providers).

Ayway, thanks for you answers.

**Comment by philipobenito** [comment]
Oh actually yeah I see the problem, the inflector won't be available until something is called via that service provider, so it is the opposite of what I said, move everything to `boot`, sorry about that, I misunderstood.

-------- Original Message --------

**Comment by Arcesilas** [comment]
Ok. So it's okay to move a definition to the boot method. I was wondering it it was a good practise or not.
Thanks!

**Comment by philipobenito** [comment]
Yeah, I hadn't noticed that it was an inflector you were trying to use, sorry. Stuff like that is what `boot` is for.

**Comment by Arcesilas** [comment]
So,  `register` if for servicves lazy loading, while `boot` is for instant loading. And since `boot` is always run, it's a good place to add inflector, configuration, etc. I was really considering what was the best practice. Like Jimmy Nash said, I can see clearly now.

**Comment by philipobenito** [comment]
Yes, exactly that, a while since I first wrote the code so took me a while to remember haha

-------- Original Message --------
