### ISSUE TITLE
Package container-interop/container-interop is abandoned

### ISSUE THREAD

**Issue by texelate** [thephpleague/container#193]
Hi,

I am using v2 and when you install using composer you get:

> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

I am just checking am I okay using v2 indefinitely via composer?

Thanks!

**Comment by philipobenito** [comment]
v2 is fine for continued use, `container-interop/container-interop` was an interim package before the PSR had passed, while it is abandoned, it is only interfaces that match the PSR interfaces.

**Comment by texelate** [comment]
Thanks @philipobenito  for the fast reply and your work on this!
