### ISSUE TITLE
Reflection container attempting to inject interface/abstract name as string rather than default value when abstract does not have a concrete

### ISSUE THREAD

**Issue by hetangyuese** [thephpleague/container#199]
https://github.com/thephpleague/container/blob/1040b51b97288f60e018424dd311041c665269c9/src/Argument/ArgumentResolverTrait.php#L71

```php
if ($class !== null) {
    $reflection_class = new \ReflectionClass($class->name);
    if (!$reflection_class->isInterface() && !$reflection_class->isAbstract()) {
        return $class->getName();
    }
}
```

**Comment by philipobenito** [comment]
I'd need a little more context on what issue exists/what problem this solves...

**Comment by hetangyuese** [comment]
> I'd need a little more context on what issue exists/what problem this solves...

```php
<?php
require __DIR__ . '/vendor/autoload.php';

class Test
{
    public function __construct(?\Psr\SimpleCache\CacheInterface $cache = null)
    {
        if ($cache) {
            $this->cache = $cache;
        }
    }
}

$container = new \League\Container\Container;

$container->delegate(
    new \League\Container\ReflectionContainer
);

$test = $container->get(\Test::class);
```

![image](https://user-images.githubusercontent.com/12309272/82188542-9e2d6600-9920-11ea-8d4f-b4d1dd58b006.png)

**Comment by philipobenito** [comment]
I'm still not sure what your problem is?

Are you saying that if there is an optional argument and it can't resolve a class, pass `null`?

**Comment by philipobenito** [comment]
I think I see what you're saying here, it is definitely a bug, but the solution isn't as simple as what is suggested above. I will investigate further.

**Comment by hetangyuese** [comment]
> I'm still not sure what your problem is?
> 
> Are you saying that if there is an optional argument and it can't resolve a class, pass `null`?

My English is poor, it's difficult to communicate, sorry

**Comment by philipobenito** [comment]
Does what I have changed the issue title to make sense?

**Comment by orbex** [comment]
Running into the same type of error when upgrading from v3.2.2 to v3.3.1
`"exception": "TypeError",
    "message": "Argument 2 passed to Api\\Controllers\\Publisher\\MaterialController::getAllAdGroups() must implement interface Psr\\Http\\Message\\ServerRequestInterface, string given"`

**Comment by orbex** [comment]
To me, yes, a little ;)
Ran into the same type of error:
`"exception": "TypeError",
"message": "Argument 2 passed to Api\\Controllers\\Publisher\\MaterialController::getAllGroups() must implement interface Psr\\Http\\Message\\ServerRequestInterface, string given"`
`	 * @param \Api\Middleware\Paginator $paginator
	 * @param \Psr\Http\Message\ServerRequestInterface $request
	 * @param \Psr\Http\Message\ResponseInterface $response
	 * @return \Psr\Http\Message\ResponseInterface
	 */
	public function getAllAdGroups(Paginator $paginator, ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
`

**Comment by philipobenito** [comment]
Solved in the latest release, with improvements to how it's handled in the 4.x branch
