### ISSUE TITLE
Status Check and Possible Feature Request

### ISSUE THREAD

**Issue by maiorano84** [thephpleague/container#200]
Just wanted to check in and see what the roadmap looked like for v4.0. I've been using league/container across a few projects and I've always found it to be easier to use than most.

I've released a [quick addon package](https://github.com/maiorano84/league-container-config) (PHP 7.4 only) that offers a Builder Pattern for constructing Container instances out of arrays that can be either stored and parsed as separate config files (PHP, JSON, XML, YAML, etc.) or passing everything in all at once.

It's fully unit-tested and I'm sticking to some pretty strict code quality standards, so hopefully it might be something to consider rolling into the 4.0 release. I could probably do this myself too if needed.

Are you guys in need of any contributors? I see that code features and contributions appear to be pretty sparse recently outside of documentation and tests, so I don't know if maintenance is being phased out, or if there are any major plans for this in the future.

Let me know your thoughts, I'd love to see development on this library continue to evolve.

**Comment by philipobenito** [comment]
v4 is due soon, had some personal stuff going on so it's been a slower process than normal. There isn't going to be too much of a change other than introducing language features. But there is a big addition in that I'm working on a way to build a compiled container to improve performance.

Will take a look at your package when I get a moment.

**Comment by maiorano84** [comment]
Thank you for taking the time to respond. Totally understand.

I'll leave this open in case this is something you feel has merit, but if it's something that you'd sooner pass on, no worries.

**Comment by philipobenito** [comment]
Compiler work is ongoing, won't be in 4.0 but aiming for 4.1 hopefully, will close this just for housekeeping
