### ISSUE TITLE
Feature: Cached factory delegate container

### ISSUE THREAD

**Issue by adrianmiu** [thephpleague/container#203]
This feature has started from the idea of combining the ReflectionContainer functionality with the self-discoverable factories (see issue #202 ). This is how it should work

This "CacheReflectionContainer" delegate container would use autoreflection to find the dependencies of an auto-wired class and would generate a file on disk containing a "Factory" class which can be auto-loaded. The end result would be a file like so:

```php
namespace League\Container\AutowiredFactories;

class Factory_{sha1_of_the_class_name} implements Factory
{
   public function __invoke(ContainerInterface $container) {
       return new class_name($container->get('param1'), $container->get('param2');
   }
}
```

**Comment by philipobenito** [comment]
I’m currently working on a tool to compile a container, but that’s with explicit definitions and not with reflection.

I do see the benefit of this for people who use reflection but I really try to discourage the use of it so I’d struggle to put something like this in to the main repository.

I wouldn’t be against linking to something from the docs though that could do this.

**Comment by adrianmiu** [comment]
> I’m currently working on a tool to compile a container, but that’s with explicit definitions and not with reflection.
It would be hard to compile the container with reflection anyway (you would most likely find false positives)
> I wouldn’t be against linking to something from the docs though that could do this.
You mean linking to a third-party/community package? If so, that would be an endorsement and it would be hard to track its development

**Comment by philipobenito** [comment]
The tool I’m building has an interactive element, would be quite easy to do but would introduce a bunch of complexity that I don’t really want.

It very much wouldn’t be an endorsement, just a “I don’t recommend reflection but if you insist on using it, this exists” but in more words with the reasoning.

**Comment by philipobenito** [comment]
Closing this as work is ongoing on a compiler
