### ISSUE TITLE
Allow to create a new instance even if it is a singleton

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#21]
Singletons make sense in a normal application context. However in some cases you want to create a completely new instance of a singleton.

Use case: default DB connection, new DB connection used elsewhere.

**Comment by hannesvdvreken** [comment]
I would use a different technique for that. Eg registering different singletons:

Eg:
```php
$container->singleton('db', function () {
   return $container->get('db.connection');
}

$container->singleton('db.instance2', function () {
    return $container->get('db.connection');
}

$container->add('db.connection', function () {
    return new DB();
}
```

Or something like that. Would that be suitable for the use case you had in mind?

**Comment by sagikazarmark** [comment]
I don't think that's the way it should be solved. This forces you to
overwrite application logic to solve a simple case.

**Comment by philipobenito** [comment]
There are actually several ways to achieve this without complicating the container itself, all of these extra checks will slow down the container, when it's original goal was to be lean and quick. I think it is an edge case and therefore since it's possible to achieve, I doubt there is enough benefit to putting this in to the container.

**Comment by sagikazarmark** [comment]
Possible? How? (without messing with special registering, which makes it a
real service locator)

Also, extra condition? It is the same as the get method, but WITHOUT the
check for singleton.

**Comment by sagikazarmark** [comment]
@philipobenito How exactly is it possible? .... Se the comment above

**Comment by philipobenito** [comment]
Just simply attaching the instances to two separate aliases

**Comment by philipobenito** [comment]
Especially with the new service provider functionality, one service provider could handle a part of your system that needs one instance, another could handle where another instance is needed

**Comment by sagikazarmark** [comment]
The point is that I want a service resolved as a new one without caring about how it is registered and without creating the same definition twice. As I said it is the same as get without checking for being a singleton or not.

**Comment by philipobenito** [comment]
So why not just use get? I'm struggling to see any benefit, most services or objects that you register will need to be a new instance every time which is default behaviour. If a singleton is needed then it is registered as that, if you need 2 separate singletons of the same object, you simply have to register 2 aliases, this is such an edge case that the functionality does not need to be in the container itself, it can be achieved very easily without being there, adding it is just adding more complexity when the aim of the container is to allow you as a developer to do what you want to do, not do everything for you as if that was the case it would grow out of control with the amount of edge cases we'd have to cover.
