### ISSUE TITLE
[question] Shared Objects

### ISSUE THREAD

**Issue by hakuno** [thephpleague/container#211]
Hey!

I read the docs.

I've a question at here https://container.thephpleague.com/3.x/definitions/ concerning Shared Objects.

> We can tell a definition to only resolve once and return the same instance every time it is resolved.

Do the Shared Objects preserve their internal data persisted in memory?

Is that like Singleton? Can I rely on that and update the data?

I need to update the data and keep using it.

Thanks!

**Comment by hakuno** [comment]
In my scenario it doesn't store value as Singleton. I can store the value in some static property to share on whole application following the said design pattern.

But...

👎 I can't do the same with Container. The `setShared` makes no difference.

Don't I get the point?

The Container seemed to make the stuff organized with IoC. However I can't rely on it yet.

**Comment by philipobenito** [comment]
An object is always by reference so yes it will persist data during a single request/process.
