### ISSUE TITLE
[2.x] Add support for PHP 8

### ISSUE THREAD

**Issue by Chi-teck** [thephpleague/container#218]
PHP 8 support for 3.x branch has been added in https://github.com/thephpleague/container/pull/205
However many projects are still using version 2.x. For instance [current stable version of Robo](https://github.com/consolidation/Robo/blob/2.2.1/composer.json#L30).

The funny thing here is that Composer downgrades this package to version 2.2.0 when resolving dependencies on PHP 8. That's possible because version 2.2.0 is formally [compatible](https://github.com/thephpleague/container/blob/2.2.0/composer.json#L24) with PHP 8.

**Comment by philipobenito** [comment]
Going to do some housekeeping this week, will sort all versioning and support out with that and get patch releases out when they're done.

**Comment by philipobenito** [comment]
Support for PHP8 has been added to 2.x, however, I strongly recommend upgrading to 3.x or the upcoming 4.x
