### ISSUE TITLE
Allow an invokable to be passed as an argument to a definition

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#22]
I am thinking about this for a long time now, and I think that from the outside invokables and aliases have only one difference: different resolving method. But I think letting invokables to be passed as an argument would be a good feature.

**Comment by hannesvdvreken** [comment]
Can you add an example?

**Comment by sagikazarmark** [comment]
My current use case:

HMVC requests are stored in a stack (which is stored in the container). ViewManagers need the current request injected which could be decided based on a callback, retrieved from the container.

I know it's something like a service locator, but...

Anyway, invokables are similar to aliases. They are actually callable definitions, without a way to make them singleton. So why shouldn't we use them like aliases?

**Comment by hannesvdvreken** [comment]
Could you add code samples? Do you mean `$container::invokable()`? In that
case: it can be invoked with different arguments so what would be the
difference between singleton and non-singleton?

**Comment by philipobenito** [comment]
If I understand what you're asking the main reason for not doing this again is complexity, the container is capable of achieving this (with a little messing around) without adding extra complexity to the package itself.

**Comment by sagikazarmark** [comment]
@philipobenito any advice how to do that? (Let me guess: add the invokable as a definition)

But this solution makes me think about the necessity of invokables.

**Comment by philipobenito** [comment]
Invokables are simply there for invoking a callable, you don't have to give any thought to the object or lack of object so when dealing with objects my advice would be to define them directly, to use the invokable functionality would be using something that's aimed at a different task.

**Comment by philipobenito** [comment]
@sagikazarmark if you can provide me with code examples where this would be a benefit we can discuss this more, however, I don't currently see the value
