### ISSUE TITLE
Inconsistent Behavior

### ISSUE THREAD

**Issue by alanondra** [thephpleague/container#222]
Environment:
- Windows 10 x64
- PHP 8.0.1
- Package Version 3.3.4

So far in most cases where I'm using the Container, it seems to work pretty well. But I'm starting to get instances where the reflection just stops working altogether.

In many cases simply binding a concrete class to an abstract interface, or just sharing a concrete class on its own, just works. But it's behaving very inconsistently with some new structures I'm adding to my application.

For instance, I'm now having to explicitly set constructor arguments. In other places in my code, this does not have to be done.

	$adapterDefinition = $container
		->share(ExceptionResponseAdapter::class)
		->addArguments([
			ResponseFactoryInterface::class,
			StreamFactoryInterface::class
		]);

I can retrieve and dump instances of those requirements before creating this definition and the container resolves them without issue, so I know it's not a matter of those dependencies failing to resolve. However, not explicitly setting the arguments here results in a 'too few arguments' error.

Likewise, it doesn't attempt to resolve dependencies with `addMethodCall` being given a class name, and instead passes said class name directly to the method, which obviously fails with a type error.

	$adapterDefinition->addMethodCall('pipe', [$strategy]);

I have again confirmed that it's able to successfully resolve the `$strategy` independent of this, so I know the dependency isn't failing, and the container is simply refusing to follow instructions.

**Comment by philipobenito** [comment]
It's hard to see exactly what you're doing without seeing all of your definitions but ai suspect you're trying a combination of defined/reflection. In which case it works one or the other, if you define a service without it's arguments the container won't attempt to reflect.

**Comment by brenoroosevelt** [comment]
I had the same problem. Here's the scenario:

```php
interface EntityManagerInterface {}

class ConcreteEntityManager implements EntityManagerInterface {}

interface UserRepositoryInterface {}

class ConcreteUserRepository implements UserRepositoryInterface
{
    public function __construct(EntityManagerInterface $em) {}
}

class UserService
{
    public function __construct(UserRepositoryInterface $repository) {}
}
```
```php
 // arrange
$container = new Container();
$container->delegate(new ReflectionContainer());

$container->add(EntityManagerInterface::class, ConcreteEntityManager::class);
$container->add(UserRepositoryInterface::class, ConcreteUserRepository::class);

// act
$entityManager   = $container->get(EntityManagerInterface::class);   // <<<----------- Ok!
$concreteUserRepository = $container->get(ConcreteUserRepository::class); // <<<----------- Ok!
$userRepository  = $container->get(UserRepositoryInterface::class); // <<<----------- Got Error!
$service = $container->get(UserService::class); // <<<----------- Got Error!
```
My questions:
1. If the container can resolve ConcreteUserRepository, why autowire cannot resolve an UserRepositoryInterface with an instance of ConcreteUserRepository?
2. Why extra configurations is required (`addArguments()`) if the container knows and is managing EntityManagerInterface?

**Comment by alanondra** [comment]
> It's hard to see exactly what you're doing without seeing all of your definitions but ai suspect you're trying a combination of defined/reflection. In which case it works one or the other, if you define a service without it's arguments the container won't attempt to reflect.

It's all reflection.

**Comment by alanondra** [comment]
Container setup:

	$container = new League\Container\Container();

	$container->delegate(
		new League\Container\ReflectionContainer()
	);

Inside a Provider:

	$this->leagueContainer->share(ExceptionResponseAdapterInterface::class, function () {
		die('never runs');
		return new ExceptionResponseAdapter([]);
	});

	$this->leagueContainer->share(ExceptionHandlerInterface::class, ExceptionHandler::class);

	// dies: too few arguments, expects 1, gets 0
	var_dump($this->leagueContainer->get(ExceptionHandlerInterface::class));
	exit;

The ExceptionHandler class:

	// AbstractExceptionHandler implements ExceptionHandlerInterface
	class ExceptionHandler extends AbstractExceptionHandler
	{
		public function __construct(protected ExceptionResponseAdapterInterface $exceptionResponseAdapter)
		{
			//
		}
	}

**Comment by philipobenito** [comment]
I don’t see the service provider being added to the container?

**Comment by alanondra** [comment]
I'm just using `$container->addServiceProvider(LoggingProvider::class);`

**Comment by philipobenito** [comment]
My point is that I can’t debug it without seeing the whole thing, nothing missing

**Comment by alanondra** [comment]
Okay, I'll just have to make a whole new project and attach it I guess? Right now aside from a bunch of code for the stuff I'm doing _with_ my application that has nothing to do with this package, the related code is a barebones use of your package. I'll upload an example of it not working later.

**Comment by alanondra** [comment]
Just a plain file:

	<?php

	require_once 'vendor/autoload.php';

	interface IFoo
	{
		//
	}

	class Foo implements IFoo
	{
		//
	}

	interface IBar
	{
		//
	}

	class Bar implements IBar
	{
		public function __construct(protected IFoo $foo)
		{
			//
		}
	}

	try {
		$container = new League\Container\Container();
		$container->delegate(new League\Container\ReflectionContainer());

		$container->add(IFoo::class, Foo::class);
		$container->add(IBar::class, Bar::class);

		var_dump($container->get(IBar::class));
	} catch (Throwable $exc) {
		printf(
			"%s # %d: %s (%s:%d)\n",
			get_class($exc),
			$exc->getCode(),
			$exc->getMessage(),
			$exc->getFile(),
			$exc->getLine()
		);
	}

Running with `php -f test.php`:

	ArgumentCountError # 0: Too few arguments to function Bar::__construct(), 0 passed and exactly 1 expected (/home/alan/Workspace/Container Test/test.php:22)

**Comment by philipobenito** [comment]
You haven’t added IFoo as an argument for IBar

**Comment by alanondra** [comment]
Yes. I shouldn't have to.

**Comment by philipobenito** [comment]
Erm, yes you should, it doesn’t mix reflection and definitions, and won’t ever going forward.

**Comment by alanondra** [comment]
Noted.
