### ISSUE TITLE
Returning from an inflector

### ISSUE THREAD

**Issue by tdtm** [thephpleague/container#228]
Rather that mutate the value with the inflector, I'm hoping to replace it entirely by creating a proxy around the object returned by the container (https://github.com/Ocramius/ProxyManager).

But currently, inflectors don't return, they only mutate.

Is this:
1. a deliberate design decision, or 
2. just something that wasn't needed (and that could potentially be added)?

Simplified example:
```php
class RepositoryServiceProvider extends \League\Container\ServiceProvider\AbstractServiceProvider implements \League\Container\ServiceProvider\BootableServiceProviderInterface
{
    public function boot() : void
    {
        $this->leagueContainer->inflector(Cachable::class,
            function (Cachable $repository) : Cachable {
                if ($this->container->get('settings.cache')) {
	                // create a proxy
    	            return $this->container(CacheProxyFactory::class)->createProxy($repository);
                }

				// return the normal, non-proxied, non-cachable one
				return $repository;
            });
    }
}
```

**Comment by tdtm** [comment]
Just to clarify, I'd look into submitting a PR myself if the answer is 2, I'd just like a go-ahead first!

**Comment by hannesvdvreken** [comment]
Have you tried:

```php
$this->leagueContainer->inflector(Cachable::class, function (Cachable &$repository): void {
    $repository = $this->container(CacheProxyFactory::class)->createProxy($repository);
}
```

**Comment by hannesvdvreken** [comment]
and the answer is 1) it's by design.

See https://github.com/thephpleague/container/blob/3.x/src/Inflector/InflectorAggregate.php#L43-L57

**Comment by philipobenito** [comment]
Sorry about the late reply on this, been having a mental couple of months.

I’ll take a deeper look tomorrow at the query and give a detailed answer.

**Comment by tdtm** [comment]
@philipobenito: No worries, I understand. Take care of yourself!

---

@hannesvdvreken 

> Have you tried:
> 
> ```php
> $this->leagueContainer->inflector(Cachable::class, function (Cachable &$repository): void {
>     $repository = $this->container(CacheProxyFactory::class)->createProxy($repository);
> }
> ```

That's always an option, but I'd rather avoid references as much as possible.

---

With that said... on second look I now realize that I can just implement my own `InflectorAggregateInterface`, that I pass to the `ContainerFactory`, and that does use the return value, which is a perfectly adequate solution!

Basically the same as the included `InflectorAggregate`, but replacing its `inflect` method with:
```php
    /**
     * {@inheritdoc}
     */
    public function inflect($object)
    {
        foreach ($this->getIterator() as $inflector) {
            $type = $inflector->getType();

            if (! $object instanceof $type) {
                continue;
            }

            $inflector->setLeagueContainer($this->getLeagueContainer());
            $object = $inflector->inflect($object);
        }

        return $object;
    }
```

The key (and only!) difference being that the return value of the inflector overwrites `$object`, instead of being ignored.

**Comment by hannesvdvreken** [comment]
That's what "open for extension" means in Open-Closed principle (SOLID): You can alter part of the behaviour by injecting a different strategy.

Note: if previously configured inflectors don't return a value, $object will be set to null.

**Comment by tdtm** [comment]
Yes totally, that's perfect! Glad the design was structured in a way to allow it 👌

I should have thought of looking at that possibility from the beginning. All good, so closing 🚀
...unless maintainers would like to have that alternative inflector strategy available in the package, in which case I'd be happy to PR it as a separate addition along with appropriate tests.


> Note: if previously configured inflectors don't return a value, $object will be set to null.

Good point to keep in mind when implementing this, thanks!
