### ISSUE TITLE
Can't seem to add values from a service provider

### ISSUE THREAD

**Issue by hassankhan** [thephpleague/container#24]
Hi, not quite sure if it's just me being stupid or this just not being possible:

```php
use League\Container\Container;
use League\Container\ServiceProvider;


class MyServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->getContainer()['key'] = 'value';
    }
}

$container = new Container();
$container->add(new MyServiceProvider);
var_dump($container->get('key'));
```

It throws:
```bash
Fatal error: Uncaught exception 'League\Container\Exception\ReflectionException' with message 'Unable to reflect on the class [key], does the class exist and is it properly autoloaded?' in /Volumes/Data HD/Dropbox/Projects/snap/vendor/league/container/src/Container.php on line 401
```

I've used Pimple in the past and this seems to work just fine :confused:

**Comment by philipobenito** [comment]
Fix applied, `composer update` :+1:

**Comment by hassankhan** [comment]
Awesome, thanks!

**Comment by philipobenito** [comment]
Not a problem, thanks for the report. Was an oversight removed in a previous release.

**Comment by hassankhan** [comment]
Sorry to be a bother, that snippet is still causing the same error

**Comment by philipobenito** [comment]
Hmmm, strange, has the update definitely pulled down? v1.3.1? If it
definitely has I will investigate some more a little later.

**Comment by hassankhan** [comment]
Just deleted the `vendor` directory and ran `composer install` to confirm, yep, it definitely is v1.3.1:
```bash
  - Installing league/container (1.3.1)
    Loading from cache
```

**Comment by philipobenito** [comment]
Ok, sorry about that, I'll create a test case with your snippet and investigate, will have a fix asap.

**Comment by hassankhan** [comment]
No worries, thanks again :smile:

**Comment by hannesvdvreken** [comment]
Question. Did you add add the key to the provides array?

```php
class MyServiceProvider extends ServiceProvider
{
    public function provides()
    {
        return ['key'];
    }

    public function register()
    {
        $this->getContainer()['key'] = 'value';
    }
}
```

**Comment by philipobenito** [comment]
Thanks @hannesvdvreken, completely missed that, this is your issue @hassankhan, when using a service provider you must provide an array of the aliases that it provides.

**Comment by hannesvdvreken** [comment]
Adding a test anyway. Accept a PR in a few minutes.

**Comment by philipobenito** [comment]
Cheers

On 21 February 2015 at 19:45, Hannes Van De Vreken <notifications@github.com

**Comment by hassankhan** [comment]
Thanks for the quick replies! Maybe this could be made more clearer in the docs? I might try and do a PR later too

**Comment by philipobenito** [comment]
Yes, a point should be made in the docs about the `$provides` property. PR would be much appreciated, if not, I'll add it to my list of docs improvements.

**Comment by hassankhan** [comment]
Made a PR: https://github.com/thephpleague/container/pull/26
