### ISSUE TITLE
Extends causing an infinite loop

### ISSUE THREAD

**Issue by kraftner** [thephpleague/container#240]
It seems that #220 fixed #219 in the 3.x branch but the bug still exists in the 4.x branch.

https://github.com/thephpleague/container/blob/388e992884ab75632d93dbaf4d29ec024d64b964/src/ServiceProvider/ServiceProviderAggregate.php#L72-L75

**Comment by philipobenito** [comment]
Will take a look this week

**Comment by philipobenito** [comment]
Should be fixed by #254
