### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by AlessandroAmos** [thephpleague/container#251]

**Comment by gpn273** [comment]
Equally wondering this myself. I have been attempting to upgrade a project from 3.x to 4.x, all going well until I spotted an issue whilst the container was trying to resolve a class which has nullable `?\DateTime $date = null` in the constructor. This works fine on 3.x, but not on 4.x.

I am using PHP 8.1. 

```
TypeError: DateTimeZone::__construct(): Argument #1 ($timezone) must be of type string, League\Container\Argument\ResolvableArgument given

    /var/www/vendor/league/container/src/ReflectionContainer.php:58

    DateTimeZone->__construct
    /var/www/vendor/league/container/src/ReflectionContainer.php:58
    /var/www/vendor/league/container/src/Container.php:189
    /var/www/vendor/league/container/src/Container.php:111
    /var/www/vendor/league/container/src/Argument/ArgumentResolverTrait.php:45
    /var/www/vendor/league/container/src/Argument/ArgumentResolverTrait.php:107
    /var/www/vendor/league/container/src/ReflectionContainer.php:58
    /var/www/vendor/league/container/src/Container.php:189
    /var/www/vendor/league/container/src/Container.php:111
    /var/www/vendor/league/container/src/Argument/ArgumentResolverTrait.php:45
    /var/www/vendor/league/container/src/Argument/ArgumentResolverTrait.php:107
    /var/www/vendor/league/container/src/ReflectionContainer.php:58
    /var/www/vendor/league/container/src/Container.php:189
    /var/www/vendor/league/container/src/Container.php:111
```

Although I don't want to jump ship to an alternative package if issues are being resolved, decisions may have to be made soon. Understand this is an open-source project, and the maintainer may not have time to resolve these issues anymore.

**Comment by bertramakers** [comment]
Wondering this as well. Ran into the bug reported in #240, which has a fix PR waiting to be reviewed/merged for more than half a year now (#248). Last commit on the default branch was over a 1,5 years ago.

Also, `league/route` is maintained by the same person and seems equally inactive based on the commits in the main branch and open issues without replies: https://github.com/thephpleague/route

**Comment by philipobenito** [comment]
Both are still planned to be maintained but I’ve been dealing with health issues over the past 2 years. Things will catch up as soon as they can, have some major version work on both packages partially done.

**Comment by bertramakers** [comment]
That's great to hear! Sorry you've had to deal with health issues. Love the packages so I'm happy to hear that they will still be maintained. All the best!

**Comment by philipobenito** [comment]
See https://github.com/thephpleague/container/discussions/255
