### ISSUE TITLE
[Feature Request] Apply inflectors right after the concrete is resolved

### ISSUE THREAD

**Issue by ghost** [thephpleague/container#266]
I'm not sure the title is self-explanatory...

Since a picture is worth a thousand words, here is an example (with a few files):

```php
class Logger
{
    public function log(string $message): void
    {
        echo $message . PHP_EOL;
    }
}
```

```php
interface LoggerAwareInterface
{
    public function setLogger(Logger $logger): void;
}
```

```php
use League\Container\ServiceProvider\AbstractServiceProvider;
use League\Container\ServiceProvider\BootableServiceProviderInterface;

class LoggerProvider extends AbstractServiceProvider implements BootableServiceProviderInterface
{
    public function provides(string $id): bool
    {
        return Logger::class === $id;
    }

    public function register(): void
    {
        $this->getContainer()->add(Logger::class);
    }

    public function boot(): void
    {
        $this->getContainer()->inflector(LoggerAwareInterface::class)
            ->invokeMethod('setLogger', [Logger::class]);
    }
}
```

```php
class Foo implements LoggerAwareInterface
{
    private Logger $logger;

    public function setLogger(Logger $logger): void
    {
        $this->logger = $logger;
    }

    public function doSomething(): void
    {
        $this->logger->log('Doing something');
    }
}
```

```php
use League\Container\ServiceProvider\AbstractServiceProvider;

class FooProvider extends AbstractServiceProvider
{
    public function provides(string $id): bool
    {
        return Foo::class === $id;
    }

    public function register(): void
    {
        $this->getContainer()->add(Foo::class)
            ->addMethodCall('doSomething');
    }
}
```

And a simple test script:
```php
require __DIR__ . '/vendor/autoload.php';

$container = new Container();

$container->addServiceProvider(new LoggerProvider());
$container->addServiceProvider(new FooProvider());

$foo = $container->get(Foo::class);
```

This script gives the following error: `PHP Fatal error:  Uncaught Error: Typed property Foo::$logger must not be accessed before initialization`

This happens because the inflector is not applied immediately when the concrete is resolved (in the Definition class), but much later, when the Container sends it. A workaround is to manualy call the setter in the `boot()` method of the Service Provider, but then the inflector becomes pointless.

Is it worth considering applying inflectors earlier (in `Definition::resolveNew()`, before `invokeMethods() is called, apparently) or is this behavior by design?

I personnally think it's worth considering (obviously), since when I invoke methods on an object reolved by the container, I expect it to be fully usable.

I've quickly tried something before opening this issue and it seems there is an infinite loop if we try to apply inflectors in Definition immediatly before the invokeMethods call...

**Comment by philipobenito** [comment]
Container isn't really designed for what you're trying to do in the example.

`addMethodCall` is there to provide dependencies that need to be provided via a method call, and by extension, inflectors are there to make it so you can define method injection for many definitions of the same type.

If you have a better real world example then I'd be happy to continue the conversation but as it stands this is more an order of operations issue in the example code.

-------- Original Message --------

**Comment by ghost** [comment]
Thanks for your quick answer!

I understand what you mean. My use case was loading configuration file and wanted the logger to be ready in order to display information on the command line. Actually, I was configuring my app, not Container. This is why I got confused.

Thanks again for your enlightening explanation as always!
