### ISSUE TITLE
Rewrite public API

### ISSUE THREAD

**Issue by philipobenito** [thephpleague/container#27]
- Separation of Concerns
- Split input and output
- Pull all reflection in to one object
- Group specific functionality
- Command line tools to create immutable container for production
- Improve service provider functionality

**Comment by hannesvdvreken** [comment]
Looking forward to see v2!

**Comment by philipobenito** [comment]
Not far away now, should have been much sooner but had a hectic couple of months

**Comment by hannesvdvreken** [comment]
No need to apologize.
