### ISSUE TITLE
Service providers are instantiated several times

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#29]
Currently every service provider, which is added to the container is instantiated by the container every time it checks a service provider. Furthermore, `setContainer` is called every time as well which is unnecessary if the service provider is already instantiated.

**Comment by philipobenito** [comment]
Correct, this was meant to be by reference but I think I lost a commit, will fix tomorrow

**Comment by sagikazarmark** [comment]
I would provide a PR for this as well, just cross-checking our solutions: I would instantiate the provider right after adding it to the container (in case of a string) and also set the container there.

This would make the code cleaner and the resolving time of aliases faster.

**Comment by philipobenito** [comment]
Just by dealing with the `$provider` variable within the loop by reference should sort this. I'd leave the setting of the container as it is inexpensive and we don't have any way to know for sure that the container has been set without calling `getContainer` which is just as expensive as re setting it.

**Comment by sagikazarmark** [comment]
Fine, will send a PR in a few minutes.

**Comment by philipobenito** [comment]
This is just a case of a small improvement, then as part of the internal rewrite for v2 I have an idea to improve it further.

**Comment by sagikazarmark** [comment]
This was my first idea, but I didn't feel the need to check the container instance in every loop.

**Comment by philipobenito** [comment]
:+1:

**Comment by sagikazarmark** [comment]
#31 pushed

**Comment by sagikazarmark** [comment]
@philipobenito Regarding the `setContainer` thing we talked about eariler, what if the container is passed as an argument in the register method? Do we really the container as a context in the service provider?

**Comment by hannesvdvreken** [comment]
I do a check if function boot exists on service providers. This is used for
registration of global exception handler etc.

https://github.com/madewithlove/semver/blob/master/app/Semver/Application.php#L70-L72

https://github.com/madewithlove/semver/blob/master/app/Semver/Services/Error/ServiceProvider.php
On 4 Apr 2015 1:58 pm, "Márk Sági-Kazár" <notifications@github.com> wrote:

@philipobenito <https://github.com/philipobenito> Regarding the setContainer
thing we talked about eariler, what if the container is passed as an
argument in the register method? Do we really the container as a context in
the service provider?

—
Reply to this email directly or view it on GitHub
<https://github.com/thephpleague/container/issues/29#issuecomment-89556506>.
