### ISSUE TITLE
BC broken with $container->add and $container->get('alias', $vars) on master branch

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/container#32]
See https://github.com/thephpleague/container/pull/28#issuecomment-77134406

- [ ] Add tests
- [ ] Fix
- [ ] Tag

**Comment by philipobenito** [comment]
1.4.* tags removed until fixed, will re-release with fix.

**Comment by hannesvdvreken** [comment]
Yeah, just created this issue for the record and because the PR is closed and is not the right place to track the progress off fixing this BC breaking bug.

**Comment by philipobenito** [comment]
Yeah, was just informing you :-)

**Comment by philipobenito** [comment]
Reverts made in master for this in prep for branching on to a v1.* development branch and v2 dropping in to master
