### ISSUE TITLE
Construction via a named constructor

### ISSUE THREAD

**Issue by tomphp** [thephpleague/container#35]
I use named constructors (static methods which return an instance of the class) fairly often. I'd really like to be able to do this with container.

It is currently possible using call and invokable but it has a different meaning semantically. And also using factory closures, but these are not possible through the config array.

I'm happy to create a PR for this but just wanted to see whether it's something which might be accepted before starting work on it.

So, what I propose is the following:

Given:
```php
<?php

final class Foo
{
    public static function fromString($string)
    {
        return new self(/* ... */);
    }

    // ...
}
```

I'd like to be able to use container like so:

```php
$container->add('Foo', ['Foo', 'fromString')->withArgument('some_value');
$foo = $container->get('Foo');
```

Also, double colon notation may be worth considering but has a danger of a BC break of anyone is using double colons in their names:

```php
$container->add('Foo', 'Foo::fromString')->withArgument('some_value');
$foo = $container->get('Foo');
```

Finally, I'd like to see it so this is possible via the config array:

```php
$config = [
    'Foo' = [
        'class' => 'Foo',  // 'Foo::fromString' could be possible also 
        'constructor' => 'fromString',
        'arguments' => [ 'some_value' ]
    ]
];
```

So thoughts? If I'd created a PR for this would it be considered?

**Comment by philipobenito** [comment]
This is something I'd have to test, but, I think what you're describing is already possible by using the named constructor essentially as a callable factory.

```php
$container->add('Foo', [new Foo, 'fromString'])
                ->withArgument('some_string');
```

What you lose here is lazy instantiation, so I would be open to the idea of `['Foo', 'fromString']` as the second argument but not until the v2.0.0 release that's coming in the next couple of weeks as it adds an extra layer of conditionals within an already complex method. v2 however, will be simplifying and splitting up much of that logic so I'd be happy to treat `['Foo', 'fromString']` as a proper callable.

Hope that helps?

**Comment by tomphp** [comment]
Hi @philipobenito,

Thanks for your reply, it makes perfect sense. I'll keep an eye open for v2 and think about it again then ;-)

Thanks,
Tom

**Comment by philipobenito** [comment]
@tomphp Just been doing some testing whilst polishing off v2 and named constructors are possible already with arrays as callables, with the first element being being an instance of the class or a string containing a FQN to the class name and the second element being the method name.
