### ISSUE TITLE
Multiple calls to the same method

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#36]
Currently you can only call a method once since method names are stored as keys of an associative array. Would be awesome if we could call a method multiple times. Use case: adding "extensions" to an object.

**Comment by philipobenito** [comment]
That's incorrect, they're stored as an indexed array with the method name and arguments attached, can call the same method as many times as you like

**Comment by sagikazarmark** [comment]
Ah, then I missed something, thanks for the correction.

**Comment by sagikazarmark** [comment]
Actually, I was referring to this: http://container.thephpleague.com/configuration/

You can only pass an associative array here.

**Comment by philipobenito** [comment]
:+1:

**Comment by philipobenito** [comment]
I see, the config stuff is getting overhauled for v2 so will take that in to consideration when parsing the config. Can't be changed in v1 as it's a BC break.

**Comment by sagikazarmark** [comment]
Looking forward to v2

**Comment by philipobenito** [comment]
Gonna be much of the same but much much tidier, back to basics and split the API up a little, it's grown a little too complex with new features and PRs being merged in. Then 2.1 or 2.2 will follow with command line tools to build immutable containers for production.

**Comment by sagikazarmark** [comment]
Any schedule? Any roadmap? Would like to help if I can.

**Comment by philipobenito** [comment]
Nearly there with a BETA, hopefully have something to show in the next week or so then league/route will follow with a v2 to be released at the same time.

**Comment by sagikazarmark** [comment]
Ah, that's the best news I've heard in the last few weeks. :+1:
