### ISSUE TITLE
Using an alias does not properly look into the Service Providers

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/container#37]
The commented line throws an error:  **Argument 1 passed to App\Users\UserMapper::__construct() must be an instance of Spot\Locator, none given**. And the second line works properly, but defeats the purpose of lazy loading.

```
// $container->add('App\Authentication\UserMapperInterface', 'App\Users\UserMapper');
$container->add('App\Authentication\UserMapperInterface', $container->get('App\Users\UserMapper'));
```
The problem seems to be with Spot\Locator being registered in a service provider. Using the commented line, the container does not look into the providers to find the service, like it does when using the get method

**Comment by hannesvdvreken** [comment]
You're actually trying to alias an interface to an implementation. I do the following:

```php
$container->add('App\Authentication\UserMapperInterface', function () {
    $container->get('App\Users\UserMapper');
});
```

**Comment by hannesvdvreken** [comment]
So I register both the `UserMapper` and `UserMapperInterface` in the same service provider.

**Comment by philipobenito** [comment]
The issue here isn't with the definition of `UserMapperInterface` but with the dependencies of the concrete `UserMapper` it has a constructor dependency of `Spot\Locator` so you need to make sure that is injected, something like the following.

```php
$container->add('App\Authentication\UserMapperInterface', 'App\Users\UserMapper')
          ->withArgument('Spot\Locator');
```

**Comment by hannesvdvreken** [comment]
The I usually do this:

```php
$container->add('App\Authentication\UserMapper')
    ->withArgument('Spot\Locator');

$container->add('App\Authentication\UserMapperInterface', function () {
    $container->get('App\Users\UserMapper');
});
```

**Comment by philipobenito** [comment]
@hannesvdvreken that's probably the best solution yes, you'll need a `use ($container)` in there but that's how I'd do it then you're keeping your concrete seperate from the abstraction. :+1:

**Comment by nebulousGirl** [comment]
What I find confusing is that <code>$container->get('App\Users\UserMapper')</code> does reflection and works without me having to add it to the container, but the following doesn't work?

```php
$container->add('App\Authentication\UserMapperInterface', 'App\Users\UserMapper');
```

I was expecting the same reflection behavior in both scenarios.

@philipobenito I can settle with your code example, just thought it could improve usability from a developer's point of view.

**Comment by philipobenito** [comment]
@nebulousGirl it was a conscious decision as reflection is slow so the idea is that if you define something, you can be aware that it's not going to reflect, that way the user has a clear choice and there's no real ambiguity about what's happening in the background.

**Comment by hannesvdvreken** [comment]
Also, you can use the container for something like this:

```php
$container->add('key', 'value');
$container->get ('key');
```

So the container can't know when you're trying to alias something or not. I suggest an alias method that adds a new closure to the container. As I described here before.

**Comment by nebulousGirl** [comment]
@philipobenito Ok, I understand your point. Is it possible to turn off reflection completely, at least from the <code>get</code> method? 

I would prefer to have the same behavior all the time, it would be less confusing.

**Comment by philipobenito** [comment]
It's something I'm playing about with on v2 (due in the next week or so), possibly having 2 separate methods, `get` and `reflect` to make it clear what is happening.

**Comment by nebulousGirl** [comment]
That would be great. Keep up the good work, I'm eagerly awaiting v2 of Container and Route.

**Comment by sjparkinson** [comment]
I got caught out by this limitation on the weekend. I'm interested to hear how v2 is going.

I'd also suggest adding something to the documentation if it does change. An example on binding a concrete to an interface in the Auto Dependency Resolution section would be useful!

**Comment by philipobenito** [comment]
I don't think it would be prudent to backport any of this to v1 but v2 has been built around the idea of being much more explicit about when and where reflection will happen, this is mainly to allow for compilation of an immutable container with no abiguity of what is being resolved. I'll close this now as my development copy will be pushed to master hopefully over the weekend with a period of time set aside for discussion and improvements before tagging the release.
