### ISSUE TITLE
Add string escaping

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#41]
In some cases an argument can be a class name (eg. a doctrine entity name). In this case I don't want the container to instantiate the class, but pass it as is. To achieve this, there could be a string escaping/expression function/wrapper object (which then gets removed during argument resolution).

**Comment by philipobenito** [comment]
:+1: will have a play with how best to do this

**Comment by sagikazarmark** [comment]
The easiest way would be to add an escape class which is then resolved as a string.

**Comment by nebulousGirl** [comment]
+1, Got around it using a closure instead of the withArguments method, but it doesn't feel right.

**Comment by philipobenito** [comment]
v2 is going to handle this with a `RawArgument` object, allowing for further manipulation and additional features down the line.

I'll close this here as it is implemented in my development copy, will be pushing to master hopefully this weekend for discussion before tagging.
