### ISSUE TITLE
Container's singleton method not in documentation.

### ISSUE THREAD

**Issue by markwardle** [thephpleague/container#44]
I think you have a fantastic project here.  It is lightweight and has everything that is needed for an IoC container.  One problem I had when trying to learn the container was in how to add singletons to the container.  The documentation has no reference to the container's singleton method.  I feel as though it should be.  I will gladly write it myself and submit a pull request if there are no objections to adding this.

**Comment by hannesvdvreken** [comment]
no objections here. I'm surprised there is no documentation on singletons

**Comment by philipobenito** [comment]
I'm also surprised and I wrote it lol :+1:
