### ISSUE TITLE
Cannot add items from config after initialisation

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/container#47]
Is there a reason why the function addItemsFromConfig is protected? I want to use it inside a ServiceProvider, is it a bad idea?

**Comment by philipobenito** [comment]
It was originally just a convenience method for processing config passed to the constructor. I think it would be straight forward to just change the accessibility but I'll need to check to make sure that it doesn't override anything. :+1:

**Comment by philipobenito** [comment]
This will now be handled by a separate package containing a config service provider and factory.
