### ISSUE TITLE
Leading backslash in class name

### ISSUE THREAD

**Issue by thik** [thephpleague/container#48]
Should I use a leading backslash in class name when register new class:
`$container->add('\SomeNS\ClassName');`
instead of:
`$container->add('SomeNS\ClassName');`
What's difference?

**Comment by philipobenito** [comment]
Either will work fine

**Comment by thik** [comment]
in this example:
```php
interface RepositoryInterface {}
class Repository implements RepositoryInterface {}
class Controller
{
    function __construct(RepositoryInterface $repo) {
    }
}

$container = new League\Container\Container;
$container->add('RepositoryInterface', 'Repository');
$controller = $container->get('Controller');
```
if i use 
`$container->add('\RepositoryInterface', '\Repository')`
instead of:
`$container->add('RepositoryInterface', 'Repository')`
it will cause a fata error.

**Comment by philipobenito** [comment]
Well in this example you're allowing the container to try to resolve the dependency automatically where the leading namespace separator will not work. But if you define the controller with it's dependency then it will work.


```

$container->add('Controller')->with argument('\RepositoryIntetface');

```





—
