### ISSUE TITLE
Question: Disabling auto-wiring if needed?

### ISSUE THREAD

**Issue by localheinz** [thephpleague/container#58]
Coming from [`Zend\ServiceManager\ServiceManager`](https://github.com/zendframework/zend-servicemanager/blob/master/test/ServiceManagerTest.php#L210-L217), I wondered if anyone besides me would find it useful if the `Container` could be configured to throw exceptions when it is attempted to retrieve a service which 

* isn't registered
* isn't provided by any of the registered service providers

What do you think?

/cc @alucic

**Comment by nebulousGirl** [comment]
I did something similar by extending the container class, but I send notices to a logger when reflection is used instead.
On Jul 27, 2015 09:02, Andreas Möller <notifications@github.com> wrote:Coming from Zend\ServiceManager\ServiceManager, I wondered if anyone besides me would find it useful if the Container could be configured to throw exceptions when it is attempted to retrieve a service which 

isn't registeredisn't provided by any of the registered service providers

What do you think?

/cc @alucic

**Comment by philipobenito** [comment]
v2 which is due later this week/weekend will disable auto wiring by default unless you explicitly tell it to do so. I think I've settled on exceptions being thrown for when a service is not registered.

**Comment by localheinz** [comment]
@philipobenito 

Awesome!
