### ISSUE TITLE
Question: where to define inflectors?

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/container#59]
I had an issue where I had put

```php
$this->container->inflector(ContainerAwareInterface::class)
            ->inflect('setContainer', [ContainerInterface::class]);
```

inside the `register` method of a `ServiceProvider`. The register method wasn't called because the resolved object wasn't referenced in the container as a `ContainerAwareInterface` implementation object.

**Comment by jamesdb** [comment]
Container 2 will have a BootableServiceProvider which will allow you to do this.

**Comment by hannesvdvreken** [comment]
so there will be a `BootableServiceProviderInterface`. but what if I'd have this:

```php
class AppServiceProvider extends \League\Container\ServiceProvider implements \League\Container\ServiceProvider\BootableServiceProviderInterface
{
    public function register()
    {
        //
    }

    public function boot()
    {
        $this->container->inflector(ContainerAwareInterface::class)
            ->invokeMethod('setContainer', [ContainerInterface::class]);
    }
}

class EventingServiceProvider extends \League\Container\ServiceProvider implements \League\Container\ServiceProvider\BootableServiceProviderInterface
{
    public function register()
    {
        //
    }

    public function boot()
    {
        $object = $this->container->get(ContainerAwareObject::class);
        // ...
    }
}
```

What if these are registered in the opposite way? There's shouldn't be a order constraint between serviceproviders.

**Comment by philipobenito** [comment]
@hannesvdvreken do you have a suggestion on how to achieve this? As it is, for eager loading there has to be an order constraint.

**Comment by hannesvdvreken** [comment]
Nah, I don't know. When you want to simply define this SP and make it work:

```php
class AppServiceProvider extends \League\Container\ServiceProvider
{
    protected $provides = [ContainerAwareInterface::class];

    public function register()
    {
        $this->container->inflector(ContainerAwareInterface::class)
            ->invokeMethod('setContainer', [ContainerInterface::class]);
    }
}
```

You'd need to go up the inheritance tree for every resolved object to see which interfaces it implements and which classes it extends. That's a potentially expensive reflection operation.

Maybe, just maybe:

```php
class ServiceProvider
{
    protected $inflectors = [ContainerAwareInterface::class];

    public function hasInflectorsFor($object) {
        foreach ($inflectors as $inflector) {
            if ($object instanceof $inflector) {
                return true;
            }
        }
    }

    return false;
}
```

**Comment by philipobenito** [comment]
Once you start looking in to bypassing order constraints more than I already have with the lazy loading (I know this doesn't help for inflectors) then the complexity really starts to grow.

I'm improving inflector functionality this week and that might help the situation from a user land perspective so I'll give you a shout once I've pushed that stuff.

**Comment by hannesvdvreken** [comment]
Great. No pressure. Just letting you know how I use it and what real life problems arise ;-)

**Comment by philipobenito** [comment]
Appreciated :+1:

**Comment by hannesvdvreken** [comment]
If it stays like it is now, also fine.

**Comment by philipobenito** [comment]
What I'm thinking is that there is now a service provider aggregate that stores all service providers, a second argument could be passed to the `addServiceProvider` method that are the dependency service providers of the one you are registering. That way, before `register` is invoked, the `register` method of the dependencies will be invoked (if they haven't been already).

**Comment by philipobenito** [comment]
Or they could be defined in the service provider itself in a similar way to the `provides` array/method. Thoughts?

**Comment by hannesvdvreken** [comment]
Not a fan of that. Service Providers don't really have to know which other SP can register something. If I want to hand the container my own Service Provider which builds a certain type of object in a much better way with my own dependencies...

**Comment by philipobenito** [comment]
Yeah, that's my thoughts, it's too much, but it is the only way around the order constraints.
