### ISSUE TITLE
Suggestion: Improve callable functionality and allow runtime arguments on call

### ISSUE THREAD

**Issue by Khelle** [thephpleague/container#60]
I see you are working on version 2, which probably would have option described in title properly implemented, but since it will probably take a while to release I would like to propose quick hotfix for version 1 to also has this option implemented.

Registering factory in the container could be done as registering some FactoryProxy object that would store given callable in one of its fields. During creation of object, this callable would be taken from this wrapper and call() would execute it as normal function. Thanks to that you can have Factories with param resolution. Easy, powerful, quite dirty but good enough for version 1.

What do you think?

**Comment by philipobenito** [comment]
#62 addresses this.
