### ISSUE TITLE
Include previous version docs links

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/container#75]
is it possible to keep the old docs?

Like http://glide.thephpleague.com/ or http://event.thephpleague.com/?

**Comment by philipobenito** [comment]
Yeah, will be working on that over the weekend :+1:

**Comment by hannesvdvreken** [comment]
league/route 2.0.0 comes first :-)

**Comment by philipobenito** [comment]
Yup lol

**Comment by philipobenito** [comment]
I'd forgotten about this, the way I've handled it in league/route is with a `gh-pages-v1` branch. Happy with that? Just not sure it's worth the time developing a nice switching system right now.

**Comment by philipobenito** [comment]
Fixed by c11255c09f8b11a2ea089ce6ed0a37e3039a4dfc
