### ISSUE TITLE
isRegistered behavior in Container

### ISSUE THREAD

**Issue by ChristopherCooper** [thephpleague/container#8]
It would appear that `\League\Container\Container::isRegistered` only checks the items array so for `\League\Container\Definition/ClassDefinition.php::invokeMethods` line 81, where you run the code 

```php
foreach ($method['arguments'] as $arg) {
  $args[] = ($this->container->isRegistered($arg)) ? $this->container->get($arg) : $arg;
}
```

The problem is if you try to inject a singleton using `withMethodCall` then it returns false however `$this->container->get($arg)` would actually return the correct singleton.

My use case is as follows:

```php
$container
  ->add('command.tool', 'Namespace\Command\Tool')
  ->withMethodCall('setContainer', ['League\Container\Container']);
```
( Note in this case the class `Namespace\Command\Tool` implements the trait `\League\Container\ContainerAwareTrait` )

And since the container is a singleton it is not resolved.

Is this intended behaviour? ( If not i can throw up a pull request to either change the behaviour of `isRegistered` or change this if statement to run ` OR $this->container->isSingleton($arg)` )

**Comment by philipobenito** [comment]
I'd actually fixed the same issue for Constructor arguments recently and missed it here, thanks for the spot :+1:
