### ISSUE TITLE
Inflector Factory Closures

### ISSUE THREAD

**Issue by gabrielbull** [thephpleague/container#80]
Hi,

It would be great to allow a way to have the `inflector` use a factory closure to create classes that implement an interface or extend a base class x.

For instance: 

```php
use My\ClassInterface;

$container->inflector(ClassInterface::class, function ($container, $concrete) {
    return ClassFactory::create($concrete);
});
```

What is your thought on that?

**Comment by localheinz** [comment]
@gabrielbull 

Not sure about this example, since `EntityManager::getRepository()` actually requires an argument, the fully qualified class name of the entity, right?

**Comment by gabrielbull** [comment]
Okay, bad example, but still a relevant issue.

**Comment by philipobenito** [comment]
Already possible https://github.com/thephpleague/container/blob/master/src/Container.php#L211

**Comment by localheinz** [comment]
@gabrielbull 

Hehe, no worries!

Just wondering, though, have you seen [this](https://github.com/thephpleague/container/blob/master/src/Container.php#L211-L214):

```php
public function inflector($type, callable $callback = null)
{
    return $this->inflectors->add($type, $callback);
}
```

**Comment by gabrielbull** [comment]
@philipobenito @localheinz 

They don't seem to work when using Auto Wiring. Any thought on that?

**Comment by philipobenito** [comment]
https://github.com/thephpleague/container/blob/master/src/Container.php#L105 it should be, can you provide a bigger context? A gist or something?

**Comment by gabrielbull** [comment]
Never mind, I need some more investigation. Will report back!

**Comment by gabrielbull** [comment]
I'm working on it, I am definitely not getting the expected result, I am looking for the cause.

**Comment by philipobenito** [comment]
Happy to take a look if you provide a gist of the full context.

Essentially we do the following if this helps.

```php
if ($class instanceof $inflector) {
    // apply inflectors
}
```

**Comment by gabrielbull** [comment]
https://gist.github.com/gabrielbull/e79d651d0655a152e184

I think the problem is that adding an inflector to the container is not enough, I need to add the class to the container as well.

> Fatal error: Uncaught League\Container\Exception\NotFoundException: Alias (MyNamespace\ClassTest) is not being managed by the container

Now, it would be ideal to have the container be able to understand that these classes all use the same factory since this is what I specify. Do you guys agree?

**Comment by philipobenito** [comment]
```php
$container->inflector(\MyNamespace\ClassInterface::class);
```

That line isn't actually doing anything.

**Comment by gabrielbull** [comment]
I must be drunk, give me a minute.

**Comment by gabrielbull** [comment]
Okay, I updated it but still the same issue.

**Comment by philipobenito** [comment]
You're aware autowiring is not enabled by default anymore? 

http://container.thephpleague.com/auto-wiring/

The last code snippet at the bottom of that page show's how to enable it. Then the whole thing will work.

**Comment by gabrielbull** [comment]
Thanks Phil, you're very helpful. I was able to pin-point the problem now. Here's a new Gist with that reproduces my original issue: https://gist.github.com/gabrielbull/d3674bb6b2cc81e09a97

Here's the error thrown by Container:

> Fatal error: Uncaught League\Container\Exception\NotFoundException: Unable to resolve a value for parameter (param2) in the function/method (__construct) in

**Comment by philipobenito** [comment]
The problem there is that when using Auto Wiring the container has to know what is needed by the constructor. Unfortunately it can't resolve what `$param2` is as there is no type hint or default value. I'd always recommend being explicit and defining your objects in your container whenever you can.

**Comment by gabrielbull** [comment]
Still, shouldn't it try my factory first and then fail? I am very explicit in my own code but when trying to glue other libraries in my project I cannot control that.

**Comment by philipobenito** [comment]
That's not really what the inflectors are for, they inflect and change state on already instantiated objects through invoking methods and changing properties etc. We can't evaluate the type/interface without an instantiated object, and we can't instantiate without passing in required constructor arguments.

Auto wiring will allow that process to be automated but it can only be automated to a certain point, if it has no information on what to inject, it can't inject anything.

**Comment by gabrielbull** [comment]
That's true, but if you agree that it would be good for the container auto-wiring to be able to auto-wire my example, it can be done with the `ReflectionClass` like this:

```php
class Container implements ContainerInterface
{
    private $container = [];

    public function get($id)
    {
        foreach ($this->container as $alias => $concrete) {
            $class = new ReflectionClass($id);
            if (false === $class) {
                return null;
            }
            do {
                $name = $class->getName();
                if ($alias == $name) {
                    return $concrete($this);
                }
                $interfaces = $class->getInterfaceNames();
                if (is_array($interfaces) && in_array($alias, $interfaces)) {
                    return $concrete($this);
                }
                $class = $class->getParentClass();
            } while (false !== $class);
            return null;
        }
        return null;
    }
}
```

**Comment by philipobenito** [comment]
This takes us in to the realm of slower reflection though for what I consider to be an edge case as I'd rather push people towards being explicit with their definitions instead of relying on the container to handle it for them.

**Comment by gabrielbull** [comment]
Got it, thanks for being helpful.

**Comment by philipobenito** [comment]
:+1:
