### ISSUE TITLE
How to override with using two Service Providers?

### ISSUE THREAD

**Issue by irfanevrens** [thephpleague/container#85]
Hello, I use [https://github.com/jenssegers/lean] for integrate with League\Container and Slim. I wanted to override ```foundHandler``` and ```request``` without edit ```SlimServiceProvider``` class. If I use the same name, there is no effect. How to override named items in ```$provides``` array in  ```SlimServiceProvider``` .

**Comment by hassankhan** [comment]
+1 some documentation would be awesome, I'm not quite sure if I'm doing it the right way

**Comment by hannesvdvreken** [comment]
Isn't this something you should figure out by looking into the code of jenssegers/lean?

**Comment by hassankhan** [comment]
Well I'm not using Lean at all, I'm just using Container and want to know how if there is a way

**Comment by hannesvdvreken** [comment]
So you're using your own service provider? It's not prohibited to copy the content of a service provider and use that instead of one included in a package.
Maybe show some code, then it will become more clear what your issue is exactly.

**Comment by hassankhan** [comment]
Say I have the following two classes:

```php
class Helper implements HelperInterface
{
    public function foo()
    {
        return;
    }
}

interface HelperInterface
{
    public function foo();
}

```

And these are set up in the container like so:

```php
$container->add(HelperInterface::class, Helper::class);
```

Is there any way I could replace `Helper::class` with something else at a later point?

**Comment by hannesvdvreken** [comment]
Simple answer: no you can't.

If you need different items to be returned in different places, consider using different keys:

```
$container->add('helper.type1', FooHelper::class);
$container->add('helper.type1', BarHelper::class);
```

Or replace the service provider (if it's not your own) which loads it with a service provider of your own if you never want the container to return the first type of instance.

**Comment by hassankhan** [comment]
Thanks, I was replacing the service provider already, just wanted to confirm that it was the right way of doing it :)

**Comment by hannesvdvreken** [comment]
Ok!

@philipobenito This is ready to close, I think.

**Comment by dimaxz** [comment]
> Simple answer: no you can't.
> 
> If you need different items to be returned in different places, consider using different keys:
> 
> ```
> $container->add('helper.type1', FooHelper::class);
> $container->add('helper.type1', BarHelper::class);
> ```
> 
> Or replace the service provider which registers the HelperInterface (if it's not your own) with a service provider of your own (if you never want the container to return the first type of instance).
also interested in this problem
