### ISSUE TITLE
Add Container::withRawArgument()

### ISSUE THREAD

**Issue by hassankhan** [thephpleague/container#89]
Expected behaviour:
```php
$container->share(Client::class)
            ->withRawArgument([
                'base_uri' => $config->get('base_uri'),
                'handler'  => $container->get(HandlerStack::class),
            ]);
```

Current behaviour:
```php
$container->share(Client::class)
            ->withArgument(new RawArgument([
                'base_uri' => $config->get('base_uri'),
                'handler'  => $container->get(HandlerStack::class),
            ]));
```

Would this be acceptable? I can make the PR, it just saves having to import a `RawArgument` class :smile:

**Comment by philipobenito** [comment]
Yes I'd be open to this :+1:

**Comment by hannesvdvreken** [comment]
Adding `public function withRawArgument` to the `DefinitionInterface` is a breaking change.
All implementing classes need to add that.

Also logical next step is then having an `withRawArguments` (mind the plural method name).

Last remark for @hassankhan:
in your example what you're doing is on every time you run this code, you will actually resolve the HandlerStack from the container even when nowhere in the execution of the code the Client is resolved from the container. It would be better to work with callables there.

**Comment by philipobenito** [comment]
@hannesvdvreken I'd not thought of the interface, I suppose it could just be added to the definitions without the interface or it would have to wait for the next major.

**Comment by hannesvdvreken** [comment]
You can add it to the AbstractDefinition, no problem.
But because type hinting it might not be clear when you can use it.

In the end, it's just sugar.

**Comment by hassankhan** [comment]
Hi, thanks for the tip @hannesvdvreken! I was using callables previously, I'll switch back to that then :)

**Comment by philipobenito** [comment]
Going to close this for now as but keep it in mind for the next major version.
