### ISSUE TITLE
Consider combining SignatureServiceProviderInterface with ServiceProviderInterface in 3.x

### ISSUE THREAD

**Issue by greg-1-anderson** [thephpleague/container#95]
Because I branched #94 off of #93 instead of master, GitHub marked #93 as merged once #94 goes in. Per https://github.com/thephpleague/container/pull/93#issuecomment-197786755, opening this issue for tracking purposes.

**Comment by philipobenito** [comment]
Covered by 981571d58fed8a22b15ffc96a6e318e4f6a4a783
